Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-10, with the labels that each got.

#478 Fixes identical names of some items, so vending doesn't stack it.
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/modular_armor/mark_one.dm
Labels: Fix

#379 Removes unused icons from Marine icon folder.
  code/_onclick/adjacent.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  icons/Marine/128.dmi
  icons/Marine/ai.dmi
  icons/Marine/junglewall.dmi
  icons/Marine/structures.dmi
  tgmc.dme
Labels: Removal, Sprites

#479 Fixes xeno structures getting damaged from acid smoke.
  code/modules/xenomorph/_xeno_structure.dm
Labels: Fix

#465 cads balance
  code/game/objects/structures/barricade.dm
Labels: Balance

#446 Нерф мотоцикла
  code/datums/components/riding/riding_vehicle.dm
  code/modules/vehicles/motorbike.dm
Labels: Balance

#481 Restricts toggle rouny from making xenos invisible, if there are no rouny versions.
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#482 Jump and related fixes
  code/__DEFINES/mobs.dm
  code/datums/components/jump.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#486 Снижение мили армора равагера
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Xeno, Balance

#488 Remove ship maps
  _maps/_basemap.dm
  _maps/arachne.json
  _maps/debugdalus.json
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/pillar_of_spring.json
  _maps/sulaco.json
  _maps/theseus.json
  code/__DEFINES/__game.dm
  code/datums/map_config.dm
  code/game/area/general.dm
  code/game/area/sulaco.dm
  tgmc.dme
Labels: Mapping, Removal

#386 Barrenquilla Mining Facility
  _maps/_basemap.dm
  _maps/barrenquilla_mining.json
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  code/__DEFINES/__game.dm
  code/game/area/barrenquilla_mining.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor_ground.dm
  config/maps.txt
  tgmc.dme
Labels: Mapping, Test Merge Candidate

#452 Ускорение взрывов
  code/controllers/subsystem/cellauto.dm
  code/datums/autocells/explosion.dm
Labels: Test Merge Candidate

#462 shoulder fire fix
  code/datums/jobs/job/fallen.dm
Labels: Fix, Test Merge Candidate

#492 Increases enemy ert chances if marines are winning.
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/icc.dm
  code/datums/emergency_calls/sectoid.dm
  code/datums/emergency_calls/sons_of_mars_breachers.dm
  code/datums/emergency_calls/sonsofmars.dm
Labels: Balance

#308 Xeno upgrades
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/upgrade_chambers.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/1x1building.dmi
  icons/mob/screen_alert.dmi
  tgmc.dme
Labels: Xeno, Feature, Test Merge Candidate

#503 Tank weapons feature
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/flamethrower.dm
  code/modules/projectiles/ammo_datums/rocket.dm
  code/modules/reqs/weapons.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/interiors/ammo_rack.dm
  icons/obj/armored/3x3/tank.dmi
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/3x3/tank_interior.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
Labels: Port, Marine, Feature

#502 Fixes call of younger unbuckling nested victims.
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Fix

#363 Hunter (slightly) Redone
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Xeno, Balance, Test Merge Candidate

#480 Adds map blips for ai and hivemind core.
  code/_globalvars/lists/flavor_misc.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/dead/observer/orbit.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  icons/UI_Icons/map_blips.dmi
  tgmc.dme
Labels: Feature, Sprites

#434 Points defence fixes
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/_globalvars/game_modes.dm
  code/datums/gamemodes/points_defence.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/telecomms/ground_telecomms.dm
  code/game/objects/structures/infestation_tower.dm
Labels: Stale

#504 Раннер мега шиза баф! 21 урона -> 28.
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Xeno, Balance

#507 Ammo fix
  code/modules/reqs/weapons.dm
Labels: Fix

#497 Predator WIP
  code/modules/predator/yautja/weapons/ranged.dm
  code/modules/projectiles/ammo_datums/yautja.dm
Labels: Fix, Removal, Balance

#495 Updates crash for xeno side, updates teleporter desc and teleportation price.
  code/__DEFINES/actions.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/last_stand.dm
  code/game/objects/effects/misc.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/structures/teleporter.dm
  code/modules/projectiles/projectile.dm
Labels: Fix, QoL, Balance

#505 Fixes changelog on linux, updates hyperlinks in it.
  code/datums/changelog/changelog.dm
  html/changelogs/archive/2024-10.yml
  tgui/packages/tgui/interfaces/Changelog.jsx
Labels: Fix, Merge Conflict

#490 Ап обычных хагеров до остальных, удаление бесполезных переопределений
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance, Test Merge Candidate

#493 Increases the damage of charge crush in 3 times and running over lying victims in 5 times.
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix, Xeno, Balance

#287 GL-81 grenade launcher simle buff
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Marine, Balance, Stale

#513 Talos hangar tweaks.
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/game/area/areas/shuttles.dm
  code/game/area/mainship.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/turfs/floor_types.dm
  code/modules/power/cable.dm
  icons/mob/landmarks.dmi
  icons/turf/mainship.dmi
Labels: Mapping, Sprites

#516 Fixes pipenets on Bigred.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredatmosvar1.dmm
  _maps/modularmaps/big_red/bigredatmosvar2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar4.dmm
  _maps/modularmaps/big_red/bigredatmosvar5.dmm
  _maps/modularmaps/big_red/bigredatmosvar6.dmm
  _maps/modularmaps/big_red/bigredlibraryvar1.dmm
  _maps/modularmaps/big_red/bigredlibraryvar2.dmm
  _maps/modularmaps/big_red/bigredlibraryvar3.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar1.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar2.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar3.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar4.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar5.dmm
Labels: Fix, Mapping

#517 `structure/xeno/Destroy()` now doesn't try to look for structure in critical structures if structure isn't critical.
  code/modules/xenomorph/_xeno_structure.dm
Labels: Fix

#514 Fixes most of vehicle fabricator bullshit.
  code/modules/reqs/_supply.dm
Labels: Fix

#511 Adds 0.5 second do_after for building acid wells.
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Xeno, Balance

#498 Fixes service uniform being invisible on rolling sleeves.
  code/modules/clothing/under/marine_uniform.dm
Labels: Fix

#519 Adds cargo droid for Talos.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#525 Баф бегемота
  code/__DEFINES/is_helpers.dm
  code/datums/components/deployable_item.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/projectiles/gun_system.dm
Labels: Balance

#510 New tad "Cargo"
  _maps/shuttles/minidropship_cargo.dmm
  code/datums/shuttles.dm
  code/game/objects/machinery/computer/dropship_picker.dm
  icons/UI_Icons/dropshippicker/_cargo.png
Labels: Feature

#522 Few barrenquilla fixes.
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  code/game/area/barrenquilla_mining.dm
Labels: Fix, Mapping

#521 Fixes pilotbunks door access so it can be opened by a pilot.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#483 Reorganize huds.
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/components/chem_booster.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/som.dm
  code/game/atoms/_atom.dm
  code/game/data_huds.dm
  code/game/data_huds/_data_huds.dm
  code/game/data_huds/atom_hud.dm
  code/game/data_huds/human.dm
  code/game/data_huds/machinery.dm
  code/game/data_huds/mecha.dm
  code/game/data_huds/xenomorph.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/yautja.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/vehicles/mecha/mecha_damage.dm
  icons/mob/hud.dmi
  icons/mob/hud/ammo.dmi
  icons/mob/hud/aura.dmi
  icons/mob/hud/human_health.dmi
  icons/mob/hud/human_misc.dmi
  icons/mob/hud/infected.dmi
  icons/mob/hud/intoxicated.dmi
  icons/mob/hud/job.dmi
  icons/mob/hud/reagent.dmi
  icons/mob/hud/xeno_health.dmi
  icons/mob/hud/xeno_misc.dmi
  icons/mob/hud/yautja.dmi
  tgmc.dme
Labels: Refactor, Test Merge Candidate

#506 Revert "Раннер мега шиза баф! 21 урона -> 28."
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Xeno, Balance

#530 tyr and mimir buff
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Marine, Balance

#531 nerf acidblood 15-30 >> 5-15
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Xeno, Balance

#532 Change spawn disk Magmoor
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Mapping

#529 Ports 14749, 14717, 14732, 14742, 14768, 14777, 14760, 14790, 14791, 14803
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/lv624/robotics.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/tgs_bigbury.dmm
  code/__HELPERS/game.dm
  code/__HELPERS/unsorted.dm
  code/datums/components/chem_booster.dm
  code/datums/components/harvester.dm
  code/datums/components/rotation.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/effects/spawners/random/engineering.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/window.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/codex/entries/stacks_codex.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/reqs/engineering.dm
Labels: Fix, Port

#535 Fixes misusage of update_icon in orange glasses code.
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#527 Deletes old guns from weapon spawners, also deletes boxes with it's ammo.
  _maps/map_files/Last_Stand/Last_Stand.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/objects/effects/spawners/random/weaponry.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
Labels: Removal

#526 Deletes useless clothes bundles from clothe vendor. Adds a new uniform category for it.
  code/__DEFINES/loadout.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/gloves/marine_gloves.dm
Labels: QoL

#528 Makes xeno manifest actually useful. Unifies Marine Manifest and Xeno manifest in 1 lobby button.
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/datums/datacore.dm
Labels: QoL

#540 Adds gagaga emoji
  icons/misc/emoji.dmi
Labels: Sprites, Meme

#512 Fixes x2 damage from crusher's charge, nerfs damage a bit, reorganizates it's code.
  code/__DEFINES/xeno.dm
  code/__HELPERS/spatial_info.dm
  code/game/atoms/_atom.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/window.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix, Balance

#417 Attempt to fix dupe with vend_delay and free essentials from loadout vendor.
  code/datums/loadout/loadout.dm
  code/datums/loadout/loadout_manager.dm
  code/datums/loadout/loadout_seller.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Fix, Test Merge Candidate

#500 Fixes flamethrower holster being able to refuel something besides standart fueltanks.
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/holsters.dm
Labels: Fix

#489 Defund
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Balance, Test Merge Candidate

#534 Fixes get_angle crash runtimes.
  code/__HELPERS/unsorted.dm
Labels: Fix, Test Merge Candidate

#322 Доработки и нерф равагера (Инцидент №10738)
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Balance

#499 Sorts punch_act procs, uncomments update_appearance of machinery code.
  code/__DEFINES/mobs.dm
  code/game/atoms/_atom.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/apc/apc.dm
  code/modules/power/lighting.dm
  code/modules/vehicles/__vehicle.dm
Labels: Fix

#536 Deletes royal bulwark.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Removal

#544 Adjusts acid blood splashes.
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/castedatum_facehugger.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Fix, Balance

#564 Crusher bugfix
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix

#470 Gun skins
  code/__DEFINES/dcs/signals.dm
  code/datums/jobs/job/job.dm
  code/game/objects/items.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/items_reskin.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/mob/living/login.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
  icons/mob/human_face.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/obj/items/cosmetics.dmi
  tgmc.dme
Labels: Skill issue

#556 Updates sprites of mirror, paper folders, bins, clipboards and stamps.
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  code/game/objects/effects/spawners/random/misc_item.dm
  code/modules/paperwork/folders.dm
  icons/effects/random/misc.dmi
  icons/obj/items/paper.dmi
  icons/obj/watercloset.dmi
Labels: Sprites

#555 Updates sprites of delivery packages, hanfcuffs, safe and boxes.
  icons/obj/items/items.dmi
  icons/obj/items/storage/storage.dmi
  icons/obj/items/vali_loaded(todo).dmi
Labels: Sprites

#561 Change sprites food/drink
  icons/mob/inhands/equipment/kitchen_left.dmi
  icons/obj/items/drinks.dmi
  icons/obj/items/food/bread.dmi
  icons/obj/items/food/condiment.dmi
  icons/obj/items/food/food.dmi
  icons/obj/items/food/meat.dmi
  icons/obj/items/food/mexican.dmi
  icons/obj/items/food/packaged.dmi
  icons/obj/items/food/piecake.dmi
  icons/obj/items/food/pizzaspaghetti.dmi
  icons/obj/items/food/soupsalad.dmi
Labels: Sprites

#562 Sigareti
  code/game/objects/items/tools/flame_tools.dm
  code/modules/paperwork/photography.dm
  icons/mob/inhands/clothing/lefthand_cigs.dmi
  icons/mob/inhands/clothing/lefthand_cigs_lighters.dmi
  icons/mob/inhands/clothing/righthand_cigs.dmi
  icons/mob/inhands/clothing/righthand_cigs_lighters.dmi
  icons/mob/inhands/equipment/smoking_left.dmi
  icons/mob/inhands/equipment/smoking_right.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/items/cigarettes.dmi
Labels: Fix, Sprites

#557 Chem dispenser and chemmaster sprite update.
  code/modules/reagents/machinery/chem_master.dm
  icons/obj/machines/chemical_machines.dmi
Labels: Sprites

#554 Keycard auth sprite update + emissive when blinking.
  code/__DEFINES/colors.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/security_levels/keycard_authentication.dm
  icons/obj/machines/monitors.dmi
  icons/obj/monitors.dmi
Labels: Sprites

#558 Updates button sprite.
  _maps/map_files/Talos/TGS_Talos.dmm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/line_nexter.dm
  code/game/objects/machinery/practice/medical.dm
  code/game/objects/machinery/scoreboard.dm
  code/modules/shuttle/marine_dropship.dm
  icons/obj/machines/buttons.dmi
  icons/obj/objects.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites

#568 improve speed weld geotermal generation
  code/modules/power/groundmap_geothermal.dm
Labels: Balance

#546 Change crusher damage, hod module, remove hilin, add GROZA ammo crate, add R-76 in point vend and scale ing skills on repair
  code/__DEFINES/loadout.dm
  code/controllers/subsystem/persistence.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/style_line.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/reqs/armor.dm
  code/modules/reqs/imports.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/motorbike.dm
Labels: Marine, Xeno, Balance

#569 Up speed bike with colaska
  code/datums/components/riding/riding_vehicle.dm
Labels: Marine, Balance

#567 Fixes bigred underground robotics apc cl test failure.
  code/game/area/bigred.dm
Labels: Fix

#549 Fixes linters whining.
  code/datums/components/_component.dm
  code/datums/greyscale/_greyscale_config.dm
  code/modules/admin/panels/permission_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/power/power.dm
  code/modules/security_levels/keycard_authentication.dm
  tools/ci/od_lints.dm
Labels: Fix

#570 Fix R76 and box AR-21
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#571 Fixes retrograde sentinel being invisible.
  icons/Xeno/castes/sentinel/retrograde.dmi
Labels: Fix, Sprites

#574 Change sprite drink №2
  icons/obj/items/drinks.dmi
Labels: Sprites

#576 Revert old medmodule sprite
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#584 Починил роботам доступы к вендорам
  code/datums/jobs/job/marines.dm
Labels: Fix

#578 Las pistols are now automatic.
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#589 Deletes grenade useless vars.
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Removal

#583 Баффы арты
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/reqs/explosives.dm
Labels: Balance

#553 Ребаланс R76
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Marine, Balance

#572 Fancy boxes with R76 now don't spawn dublicates of loot.
  code/game/objects/items/storage/briefcase.dm
Labels: Fix

#592 Adds more laugh sounds.
  code/game/sound.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  sound/voice/human/female/laugh_1.ogg
  sound/voice/human/female/laugh_2.ogg
  sound/voice/human/female/laugh_3.ogg
  sound/voice/human/female/laugh_4.ogg
  sound/voice/human/female/laugh_5.ogg
  sound/voice/human/female/laugh_6.ogg
  sound/voice/human/female/laugh_7.ogg
  sound/voice/human/male/laugh_1.ogg
  sound/voice/human/male/laugh_2.ogg
  sound/voice/human/male/laugh_3.ogg
  sound/voice/human/male/laugh_4.ogg
  sound/voice/human/male/laugh_5.ogg
  sound/voice/human/male/laugh_6.ogg
  sound/voice/human/male/laugh_7.ogg
  sound/voice/human/male/laugh_8.ogg
  sound/voice/human/male/laugh_9.ogg
  sound/voice/robotic/female_laugh.ogg
  sound/voice/robotic/female_laugh1.ogg
  sound/voice/robotic/female_laugh2.ogg
  sound/voice/robotic/female_laugh3.ogg
  sound/voice/robotic/female_laugh4.ogg
  sound/voice/robotic/female_laugh5.ogg
  sound/voice/robotic/female_laugh6.ogg
  sound/voice/robotic/female_laugh7.ogg
  sound/voice/robotic/male_laugh1.ogg
  sound/voice/robotic/male_laugh2.ogg
  sound/voice/robotic/male_laugh3.ogg
  sound/voice/robotic/male_laugh4.ogg
  sound/voice/robotic/male_laugh5.ogg
  sound/voice/robotic/male_laugh6.ogg
  sound/voice/robotic/male_laugh7.ogg
  sound/voice/robotic/male_laugh8.ogg
  sound/voice/robotic/male_laugh9.ogg
  sound/voice/robotic/male_laugh_1.ogg
  sound/voice/robotic/male_laugh_2.ogg
  sound/voice/silly_laugh.ogg
Labels: Sound

#573 Change some machines sprite
  code/game/objects/machinery/air_alarm.dm
  icons/obj/machines/air_alarm.dmi
  icons/obj/machines/apc.dmi
  icons/obj/machines/fire_alarm.dmi
  icons/obj/objects.dmi
  icons/obj/power.dmi
  icons/obj/status_display.dmi
Labels: Sprites

#548 Update trap sprites.
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/xenomorph/trap.dm
  icons/Xeno/Effects.dmi
Labels: Sprites

#545 Buffs valkyrie module.
  code/datums/components/suit_autodoc.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/reqs/armor.dm
Labels: Balance, Grammar and formatting

#566 Cas weaponry doesn't fit on other shuttles now.
  code/__DEFINES/objects.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#581 Optimize gibs mapload.
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/recycling/disposal.dm
Labels: Optimization

#523 Last stand now has few spawn points for waves.
  _maps/map_files/Last_Stand/Last_Stand.dmm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/objects.dm
  code/datums/wave_spawner.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Mapping, Feature

#560 Bump and directional attacks now check for iff signals instead of faction. Enemy factions can now strip dogtags id's instead of info tags.
  _maps/predator/huntership.dmm
  code/__DEFINES/factions.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/predators.dm
  code/datums/actions/observer_action.dm
  code/datums/components/bump_attack.dm
  code/datums/elements/directional_attack.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/objective_items.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/xeno_iff_tags.dm
  code/game/objects/structures/prop.dm
  code/modules/events/supply_drop.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix, Feature

#543 Converts apicker, jump-to, smite menu and get-server-logs to tgui. Dsay is now html.
  code/__DEFINES/speech_channels.dm
  code/datums/keybinding/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  code/modules/client/client_procs.dm
  code/modules/tgui_input/say_modal/modal.dm
  code/modules/tgui_input/say_modal/speech.dm
  tgui/packages/tgui-say/ChannelIterator.ts
  tgui/packages/tgui-say/styles/colors.scss
Labels: QoL, Administration

#538 Deletes tx54 he ammo.
  code/__DEFINES/loadout.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/codex/entries/magazine_codex.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/weapons.dm
Labels: Removal

#580 Change larvapoints from shipside roles
  code/__DEFINES/jobs.dm
Labels: Xeno, Balance, Test Merge Candidate, Do Not Merge

#559 Proper surgery button in valhalla.
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/practice/medical.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: QoL

#565 Proper lights for optable and bioprinter, so their emissives are seen.
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/bioprinter.dm
Labels: Fix

#579 You can't evolve into limited next tiers, with caste swap\regress.
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#551 `Change view` cleanup.
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/hud.dm
  code/datums/view.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/login.dm
Labels: Refactor

#575 Change sprite syringe and some janitor shmot
  _maps/map_files/Talos/TGS_Talos.dmm
  icons/obj/items/syringe.dmi
  icons/obj/janitor.dmi
Labels: Sprites

#600 Adds few cat emojis.
  icons/misc/emoji.dmi
Labels: Feature

#603 Fixes fullscreen skill issue.
  code/_onclick/hud/fullscreen.dm
Labels: Fix, Skill issue

#601 Ports playsound changes from offs.
  code/__DEFINES/dcs/signals.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/sound.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/shuttle/on_move.dm
Labels: Fix, Port

#598 Change wall flame pen and add wide spray
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Marine, Balance

#606 hunter action fix
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix
