Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-09, with the labels that each got.

#190 Fixes r500 item_states and martini_belt full state.
  code/datums/components/chem_booster.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/storage.dm
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#189 Fixes removing b7 smart scope not removing aiming traits.
  code/modules/projectiles/attachables/_attachable.dm
Labels: Fix

#192 Fixes pilot bunks on Talos.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#193 Adds rouny version of the queen, updates rouny version of ravager, deleted puppet.dmi.
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  icons/Xeno/castes/puppet.dmi
  icons/Xeno/castes/queen.dmi
  icons/Xeno/castes/ravager.dmi
Labels: Sprites

#191 Fixes basic sentries not giving out in loadout for engineers.
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/UI_Icons/map_blips.dmi
Labels: Fix

#197 Fixes revive stomach runtime.
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#199 Escape pod button fix (#16467)
  tgui/packages/tgui/interfaces/EscapePod.js
Labels: Fix

#178 Deletes squad locked vendors.
  code/__DEFINES/machines.dm
  code/_globalvars/bitfields.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal

#194 Respawn Alerts
  code/datums/gamemodes/_game_mode.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_verbs.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Feature

#173 Xeno extinguishing fire
  code/_onclick/xeno.dm
Labels: Xeno, Feature

#175 Deployable optable
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/spawners/random/medical.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/surgery_table.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/reqs/supplypacks.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/surgery.dm
  icons/obj/surgery.dmi
  tgmc.dme
Labels: Marine, Balance, Feature

#202 Points Defence clean up
  code/datums/gamemodes/points_defence.dm
  code/game/objects/items/radio/headset.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Fix

#204 Meleeproof walls fix
  code/game/turfs/walls/resin.dm
Labels: Fix

#177 tcoms, tsensor, some fix map
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/big_red/operation.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Mapping

#188 Acid code cleanup.
  code/__DEFINES/atom.dm
  code/__DEFINES/dcs/signals.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/mounted.dm
  tgmc.dme
Labels: Refactor

#205 Ravager buff
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Fix, Balance

#218 Острая лопата 60 -> 90 = Мачете
  code/game/objects/items/tools/shovel_tools.dm
Labels: Balance, Skill issue

#211 Wide chairs
  _maps/interiors/apc_medical.dmm
  _maps/interiors/apc_transport.dmm
  _maps/interiors/tank.dmm
  _maps/shuttles/normandy.dmm
  code/game/objects/machinery/computer/dropship_weapons.dm
  code/game/objects/machinery/telecomms/machines/relay.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/shuttle/marine_dropship.dm
  icons/obj/objects.dmi
  icons/turf/dropship.dmi
  icons/turf/shuttle.dmi
Labels: Mapping, Marine, Feature

#214 Adds more tactical binoculars mode overlays (#16372)
  code/game/objects/items/binoculars.dm
  code/game/objects/items/firesupport_binoculars.dm
  icons/Marine/marine-navigation.dmi
Labels: Port, QoL

#216 Increases possible transfer amounts for hyposprays.
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: QoL

#219 Fixes tactical reload intercepting worn magazines.
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/weapons/misc.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#215 Ports Gregor campaign portraits. (#15273)
  code/datums/fire_support.dm
  code/datums/gamemodes/campaign/campaign_assets.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/rewards/allies.dm
  code/datums/gamemodes/campaign/rewards/drop_pods.dm
  code/datums/gamemodes/campaign/rewards/equipment.dm
  code/datums/gamemodes/campaign/rewards/fire_support.dm
  code/datums/gamemodes/campaign/rewards/teleporter.dm
  code/modules/screen_alert/misc_alert.dm
  icons/UI_Icons/screen_alert_images.dmi
Labels: Port, Sprites

#209 Ports qols & fixes: 14677, 14822, 15793, 15814, 15855, 16153
  code/__HELPERS/logging/attack.dm
  code/__HELPERS/mobs.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/jobs/squads.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/weapon.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/hologram.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/teleporter_array.dm
  code/game/sound.dm
  code/modules/condor/cas_shuttle.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/mapping/map_template.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/README.md
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
  code/modules/xenomorph/tunnel.dm
  tgmc.dme
Labels: Fix, Port, QoL

#223 Factory fixes.
  code/modules/reqtorio/assembly_crafts.dm
Labels: Fix

#229 Deletes death from above.
  code/game/turfs/space/transit.dm
Labels: Removal

#222 Reorgs supplies list, fixes p9mm packet typepath and p9mm incendiary packet sprite, adds stuff to valhalla vendor.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/reqs/_supply.dm
  code/modules/reqs/_supplypacks.dm
  code/modules/reqs/armor.dm
  code/modules/reqs/clothing.dm
  code/modules/reqs/engineering.dm
  code/modules/reqs/explosives.dm
  code/modules/reqs/factory.dm
  code/modules/reqs/imports.dm
  code/modules/reqs/medical.dm
  code/modules/reqs/operations.dm
  code/modules/reqs/supplies.dm
  code/modules/reqs/supplypacks.dm
  code/modules/reqs/vehicles.dm
  code/modules/reqs/weapons.dm
  icons/obj/items/ammo.dmi
  tgmc.dme
Labels: Fix

#230 Tank space fix (#16492)
  code/modules/vehicles/_hitbox.dm
Labels: Fix, Port

#226 Illusion fixes and improvements (#16506)
  code/__DEFINES/mobs.dm
  code/game/objects/items/devices/mirage.dm
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/mob/illusion.dm
  code/modules/projectiles/sentries.dm
  tgmc.dme
Labels: Port, Refactor, Feature

#227 Suit autodocs now check storage contents before injecting. Health analyzer now properly makes overdosed reagents in stomach red.
  code/datums/components/suit_autodoc.dm
  code/game/objects/items/scanners.dm
Labels: Fix

#232 Applies alternative sprites from Talos to everything, except vents, scrubbers and surgery cases.
  _maps/map_files/Talos/TGS_Talos.dmm
  code/datums/components/deployable_item.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/bioprinter.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/iv_drip.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/machinery/surgery_table.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/walls/wall_types.dm
  icons/obj/iv_drip.dmi
  icons/obj/machines/camera.dmi
  icons/obj/machines/cryogenics.dmi
  icons/obj/surgery.dmi
Labels: Fix, Mapping, Sprites

#235 фикс новых стен для хайвлорда
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Fix, Xeno

#236 Includes cargo category of medical.
  tgmc.dme
Labels: Fix

#239 Acid well now doesn't spread acid smoke on destruction if it's empty.
  code/modules/xenomorph/acidwell.dm
Labels: Fix

#241 Profiler
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
Labels: QoL

#242 Fixes transport and assault crewman being locked in pilot bunks.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#247 Фикс ГЦ ИИ
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Optimization

#248 Добавляет спец. стены ХМу
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
Labels: Fix

#249 Adds missing apc's to Talos. Also changes hangar cables to be under CAS.
  _maps/map_files/Talos/TGS_Talos.dmm
  code/modules/power/cable.dm
Labels: Fix, Mapping

#246 Adds abomination icon to orbit menu.
  code/_globalvars/lists/flavor_misc.dm
Labels: QoL

#245 Cryopods on escape shuttle now look in the right direction.
  _maps/shuttles/escape_shuttle.dmm
Labels: Mapping

#257 Фикс рантайма детектора движения
  code/game/objects/items/motion_detector.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix

#258 Фикс рантайма death() и droplimb()
  code/modules/mob/living/carbon/human/death.dm
  code/modules/organs/limbs.dm
Labels: Fix

#254 Фикс рантайма remove_images_from_clients
  code/__HELPERS/game.dm
Labels: Fix

#253 Фикс рантайма медсканнера
  code/game/objects/items/scanners.dm
Labels: Fix

#255 Фикс рантайма интегрированного медсканера
  code/_onclick/item_attack.dm
Labels: Fix

#261 Visual fixes (#15012) & Minor jump tweaks (#15065)
  code/__DEFINES/layers.dm
  code/datums/components/jump.dm
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  icons/obj/structures/train.dmi
Labels: Fix, Port

#259 Fixes crash latejoin spawns and cryopod dirs on bigbury and canterbury.
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/last_stand.dm
Labels: Fix

#252 Fixes g fuel back tank having no sprite.
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/flamer.dm
  icons/mob/clothing/back.dmi
  icons/obj/items/ammo.dmi
Labels: Fix, Sprites

#251 Fixes AR-55 loadouts.
  code/datums/jobs/job/freelancers.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/belt.dm
Labels: Fix

#243 Adjacency runtime fix (#15218)
  code/_onclick/adjacent.dm
  code/game/objects/items/storage/internal.dm
Labels: Fix

#238 Optimizes shrapnel code a bit.
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/shrapnel.dm
  code/modules/projectiles/projectile.dm
Labels: Optimization

#234 Adds corpsman satchel and backpack to cargo.
  code/modules/reqs/clothing.dm
Labels: Feature

#224 Probably fixes tad breaking pipes.
  code/modules/shuttle/on_move.dm
Labels: Fix, Test Merge Candidate

#262 Понижает частоту обновления таймера способностей
  code/game/objects/effects/countdown.dm
Labels: Optimization

#208 Maybe fixes sd lights lag.
  code/modules/power/lighting.dm
  code/modules/vehicles/powerloader.dm
Labels: Fix, Test Merge Candidate

#210 Respriting something
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/machinery/telecomms/ground_telecomms.dm
  code/game/objects/structures/prop.dm
  code/game/turfs/floor_types.dm
  icons/Marine/mainship_props64.dmi
  icons/UI_Icons/map_blips_large.dmi
  icons/turf/mainship.dmi
Labels: Feature, Sprites

#231 Fixes admin Jump verb.
  code/modules/admin/admin_verbs.dm
Labels: Fix

#269 Add robot gear vendors to valhalla and crash shuttles. Also add robot and marine stripes. Also delete excessive roombas. Also update valhalla.
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/effects/decals/turfdecals/warning_stripes.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/turf/decals.dmi
Labels: Mapping

#265 Ещё один фикс стен
  code/game/turfs/walls/walls.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#276 Guns runtime fixes
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Optimization

#273 nerf and twix
  code/__DEFINES/loadout.dm
  code/datums/components/riding/riding_vehicle.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/ammo_datums/energy.dm
  code/modules/reqs/armor.dm
Labels: Fix, Balance

#266 Fixes quickclot not stopping internal bleedings.
  code/modules/organs/wound.dm
Labels: Fix

#263 Удаление функционала гидропоники
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredetavar1.dmm
  _maps/modularmaps/big_red/bigredetavar2.dmm
  _maps/modularmaps/big_red/bigredetavar3.dmm
  _maps/modularmaps/big_red/bigredetavar4.dmm
  _maps/modularmaps/big_red/bigredetavar5.dmm
  _maps/modularmaps/lv624/auxbotany.dmm
  code/game/objects/effects/spawners/random/machinery.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Removal

#284 Fixes an attachment component bug (#15982)
  code/datums/components/attachment_handler.dm
Labels: Fix, Port

#283 Бафф разбега крашера
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance, Feature

#282 Suppressor less visible
  code/modules/projectiles/projectile.dm
  icons/obj/items/ammo.dmi
Labels: Port, Feature

#286 shooting from behind the shoulder
  code/modules/projectiles/projectile.dm
Labels: Marine, Feature

#272 subsystem tweaks
  code/__DEFINES/_subsystems.dm
  code/controllers/subsystem/cellauto.dm
  code/controllers/subsystem/processing/projectiles.dm
Labels: Optimization, Balance, Test Merge Candidate, Do Not Merge

#264 Attempt to fix some of xeno harddels.
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Optimization

#280 Btr alive
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/apc.dm
Labels: Marine, Balance

#279 Morebox
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/misc.dm
  icons/obj/items/ammo.dmi
Labels: Marine, Balance

#285 Бенотрава на ЛВ теперь растет везде
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  code/game/turfs/turf.dm
Labels: Fix, Xeno

#295 Fixes medbay and maint doors on Talos.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#293 Officer swords are now acidable.
  code/game/objects/items/weapons/blades.dm
Labels: Balance

#289 Robots can now wear BE-47.
  code/modules/clothing/glasses/night.dm
Labels: Marine, Balance

#195 Fixes larva latejoin runtime.
  code/controllers/subsystem/job.dm
Labels: Fix

#228 Plushes now play sound on attack_self.
  code/game/objects/items/misc.dm
  code/game/objects/items/toys/toys.dm
Labels: Feature, Meme

#275 Fixes mob harddels, also fixes runner evasion processing post-death.
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/effects/overlays.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/organs/pain.dm
  code/modules/predator/huntdata.dm
  code/modules/tgui/external.dm
Labels: Fix, Optimization, Test Merge Candidate

#274 Attempt to fix droppod harddels.
  code/game/objects/structures/droppod.dm
Labels: Optimization

#300 Adds undeffibable check for APC gibber.
  code/game/objects/machinery/kitchen/gibber.dm
Labels: Balance

#299 keyLoop
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/mob_movement.dm
Labels: Optimization

#297 Update game.dm
  code/__HELPERS/game.dm
Labels: Fix

#301 pamphlet fix
  code/game/objects/items/pamphlets.dm
Labels: Fix

#307 clown buff
  code/datums/components/slippery.dm
  code/datums/jobs/job/clown.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/mob.dm
  icons/obj/janitor.dmi
Labels: Feature

#306 Fixes harddel of container and brainmob
  code/modules/mob/living/brain/brain.dm
  code/modules/organs/limb_objects.dm
Labels: Fix

#305 Proj code update
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/shrapnel.dm
  code/game/objects/structures/girders.dm
  code/modules/codex/entries/ammunition_codex.dm
  code/modules/codex/entries/magazine_codex.dm
  code/modules/predator/yautja/bracers.dm
  code/modules/predator/yautja/weapons/ranged.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/energy.dm
  code/modules/projectiles/ammo_datums/flamethrower.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/ammo_datums/rocket.dm
  code/modules/projectiles/ammo_datums/shrapnel.dm
  code/modules/projectiles/ammo_datums/xeno.dm
  code/modules/projectiles/ammo_datums/yautja.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/projectile.dm
Labels: Fix, Port, Refactor

#277 Adds additional check for grenade throw_at.
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Fix

#292 Fixes tad breaking pipes for real this time.
  _maps/shuttles/minidropship_big.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_food.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  code/game/objects/machinery/doors/poddoor.dm
  code/modules/power/apc/apc.dm
  code/modules/shuttle/on_move.dm
Labels: Fix

#302 SVD To marine vendor weapons (TESTING)
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Marine, Balance

#313 Fixes freyr not working.
  code/modules/organs/organs.dm
Labels: Fix

#309 Razor wire consistency.
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/razorwire.dm
Labels: Balance

#312 HP buff
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
Labels: Balance

#316 Update projectile.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#320 Revert discord stuff
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/discord.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/last_stand.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/clown.dm
  code/datums/jobs/job/job.dm
  code/modules/admin/holder.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/manipulation.dm
  code/modules/discord/tgs_commands.dm
  code/modules/mob/new_player/new_player.dm
  config/config.txt
  tgmc.dme
Labels: Test Merge Candidate, Do Not Merge

#318 Morebox2
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/misc.dm
  icons/obj/items/ammo.dmi
Labels: Balance

#332 Weedifies Lv624.
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/lv624/atmospherics.dmm
  _maps/modularmaps/lv624/auxbotany.dmm
  _maps/modularmaps/lv624/cargo_bay.dmm
  _maps/modularmaps/lv624/cargo_bay2.dmm
  _maps/modularmaps/lv624/hydro_jungle.dmm
  _maps/modularmaps/lv624/hydro_path.dmm
  _maps/modularmaps/lv624/internal_affairs.dmm
  _maps/modularmaps/lv624/lakebase.dmm
  _maps/modularmaps/lv624/lvhydrobridge2.dmm
  _maps/modularmaps/lv624/lvhydrobridge3.dmm
  _maps/modularmaps/lv624/medbayone.dmm
  _maps/modularmaps/lv624/medbaytwo.dmm
  _maps/modularmaps/lv624/newcavevar1.dmm
  _maps/modularmaps/lv624/newcavevar10.dmm
  _maps/modularmaps/lv624/newcavevar11.dmm
  _maps/modularmaps/lv624/newcavevar12.dmm
  _maps/modularmaps/lv624/newcavevar2.dmm
  _maps/modularmaps/lv624/newcavevar3.dmm
  _maps/modularmaps/lv624/newcavevar4.dmm
  _maps/modularmaps/lv624/newcavevar5.dmm
  _maps/modularmaps/lv624/newcavevar6.dmm
  _maps/modularmaps/lv624/newcavevar7.dmm
  _maps/modularmaps/lv624/newcavevar8.dmm
  _maps/modularmaps/lv624/newcavevar9.dmm
  _maps/modularmaps/lv624/robotics.dmm
  _maps/modularmaps/lv624/southsandtemple1.dmm
  _maps/modularmaps/lv624/southsandtemple2.dmm
  _maps/modularmaps/lv624/southsandtemple3.dmm
  _maps/modularmaps/lv624/southsandtemple4.dmm
  _maps/modularmaps/lv624/telecomms.dmm
Labels: Mapping

#330 Removes grenade hit sound.
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/predator/smartdisc.dm
Labels: Removal

#329 Adds fulton dnr check. Also small runtime fix.
  code/modules/requisitions/fulton.dm
  code/modules/requisitions/supply_export.dm
Labels: Fix

#328 Tank light fix
  code/modules/vehicles/armored/_multitile.dm
Labels: Fix

#327 Deletes unused stuff from vendors, minor fixes.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/projectiles/magazines/misc.dm
Labels: Fix, Removal, QoL

#326 Fixes valhalla on Last Stand.
  code/datums/gamemodes/last_stand.dm
Labels: Fix

#325 Fixes brain surgery not updating brain damage properly. Same with eyes.
  code/modules/admin/smites/brain_damage.dm
  code/modules/surgery/brainrepair.dm
  code/modules/surgery/eye.dm
Labels: Fix

#324 Fixes t25 sprites.
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/weapons.dm
  icons/Marine/gun64.dmi
  icons/obj/items/ammo.dmi
Labels: Fix

#296 Нерф линка Горжера
  code/__DEFINES/mobs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Xeno, Balance

#291 Pain cleanup.
  code/__DEFINES/dcs/signals.dm
  code/datums/components/suit_autodoc.dm
  code/datums/outfit.dm
  code/datums/quick_load_outfits.dm
  code/game/data_huds.dm
  code/game/objects/items/embedding.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_pain.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/pain.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/pain.dm
  code/modules/projectiles/gun_system.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/toxin.dm
  code/modules/surgery/surgery.dm
  tgmc.dme
Labels: Refactor

#311 Jump Jump
  code/modules/mob/living/carbon/carbon.dm
Labels: Feature

#349 Fixes sg153 magazines missing from cargo.
  code/modules/reqs/weapons.dm
Labels: Fix

#348 Fixes dummy icon runtime. (#14756)
  code/__HELPERS/icons.dm
Labels: Fix, Port

#347 Makes Chameleon Badge, Cape, Kama, and Reflective Belt Easier to Equip (#14741)
  code/modules/clothing/modular_armor/attachments/cape.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Port, QoL

#346 Remove unneeded crash message (#14714)
  code/datums/jobs/job/job.dm
Labels: Port

#345 Ghost verb now doesn't need approval if mob is on centcomm z level.
  code/modules/mob/living/living_verbs.dm
Labels: QoL

#343 Fixes health analyzer SSD display (#14712)
  code/game/objects/items/scanners.dm
Labels: Fix, Port

#339 Some fix
  _maps/map_files/Talos/TGS_Talos.dmm
  code/__DEFINES/conflict.dm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/freelancers.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  icons/mob/items_lefthand_1.dmi
Labels: Fix

#357 Buff bull
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
Labels: Xeno, Balance

#358 Бафф новых стен
  code/game/turfs/walls/resin.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Xeno, Balance

#359 Fixes sr-81 in cargo.
  code/modules/reqs/weapons.dm
Labels: Fix, Skill issue

#354 TRANSVITOX
  code/__DEFINES/mobs.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Xeno, Balance

#353 nanites some buffs
  code/modules/organs/wound.dm
  code/modules/reagents/reagents/medical.dm
Labels: Marine, Balance

#351 wall hack fix
  code/modules/vehicles/armored/_multitile.dm
Labels: Fix, Skill issue

#350 Ammofix
  code/modules/projectiles/magazines/misc.dm
  icons/obj/items/ammo.dmi
Labels: Fix

#352 hunter nerf
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Balance

#342 Fixes t25 onmob sprites
  icons/mob/clothing/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Fix, Sprites

#341 Fix a ceiling define (#14710)
  code/__DEFINES/__game.dm
Labels: Fix, Port

#361 Includes spawner in the .dme
  code/modules/xenomorph/spawner.dm
  tgmc.dme
Labels: Fix, Skill issue

#314 Ports a lot of stuff, fixes stuff.
  code/__HELPERS/game.dm
  code/_onclick/click.dm
  code/controllers/subsystem/advanced_pathfinding.dm
  code/controllers/subsystem/autofire.dm
  code/controllers/subsystem/modularmapping.dm
  code/datums/components/harvester.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/xeno.dm
  code/game/objects/structures/xeno/_xeno.dm
  code/game/objects/structures/xeno/door.dm
  code/game/objects/structures/xeno/growth.dm
  code/game/objects/structures/xeno/jelly.dm
  code/game/objects/structures/xeno/resin.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
  tgmc.dme
Labels: Fix, Port, Feature

#298 Ports sectoid psychic abilities.
  code/__DEFINES/actions.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/keybind.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/datums/actions/species_actions/sectoid_action.dm
  code/datums/emergency_calls/necoarc.dm
  code/datums/emergency_calls/sectoid.dm
  code/datums/jobs/job/necoarc.dm
  code/datums/jobs/job/sectoid.dm
  code/datums/keybinding/sectoid.dm
  code/datums/status_effects/sectoid.dm
  code/game/atoms/_atom.dm
  code/game/objects/items.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_verbs.dm
  icons/effects/64x64.dmi
  icons/mob/psionic_icons.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: Port, Feature

#365 internal bleeding scan
  code/game/objects/items/scanners.dm
  tgui/packages/tgui/interfaces/MedScanner.js
Labels: Marine, QoL

#368 Decreases xeno respawn time from 5 to 3 minutes.
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
Labels: Xeno, Balance

#369 Fixes barricade deconstruction.
  code/game/objects/obj_defense.dm
  code/game/objects/structures/barricade.dm
Labels: Fix, Port

#370 Properly weeds Prison station, also adds tunnel spawners.
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Mapping

#334 Increases cellauto subsystem priority a bit.
  code/__DEFINES/_subsystems.dm
Labels: Optimization

#344 Wheelchair refactor (#14718)
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/lv624/medbayone.dmm
  code/datums/components/riding/riding_vehicle.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/wheelchair.dm
  tgmc.dme
Labels: Port, Refactor

#362 Probably fixes getting stuck after explosion throws.
  code/game/objects/explosion_recursive.dm
Labels: Fix

#364 Xeno spit is unstaggerable
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Xeno

#372 Adds tactical reloads for revolvers.
  _maps/map_files/slumbridge/slumbridge.dmm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/reqs/weapons.dm
Labels: Marine, Feature

#375 Fixes innate/vote harddel.
  code/controllers/subsystem/vote.dm
Labels: Fix

#367 Replaces most used procs in explosions with `INVOKE_ASYNC`
  code/datums/autocells/explosion.dm
  code/game/objects/explosion_recursive.dm
Labels: Optimization

#335 Cellauto explosions fix
  code/datums/autocells/explosion.dm
Labels: Optimization, Test Merge Candidate

#383 Fixes xray gun fire delay being inconsistent.
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#381 Fixes 3 runtimes.
  code/datums/autocells/explosion.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/modules/power/apc/apc.dm
Labels: Fix

#378 Fixes pocket beam sprite disappearing on powerpack connecting.
  icons/Marine/marine-weapons.dmi
  tgmc.dme
Labels: Sprites

#384 Изменения и добавления анимаций гиба всех Ксеномомрфов
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/predalien.dm
  icons/Xeno/castes/beetle.dmi
  icons/Xeno/castes/behemoth.dmi
  icons/Xeno/castes/bull.dmi
  icons/Xeno/castes/carrier.dmi
  icons/Xeno/castes/chimera.dmi
  icons/Xeno/castes/crusher.dmi
  icons/Xeno/castes/defender.dmi
  icons/Xeno/castes/defiler.dmi
  icons/Xeno/castes/drone.dmi
  icons/Xeno/castes/facehugger.dmi
  icons/Xeno/castes/gorger.dmi
  icons/Xeno/castes/hivelord.dmi
  icons/Xeno/castes/hunter.dmi
  icons/Xeno/castes/king.dmi
  icons/Xeno/castes/mantis.dmi
  icons/Xeno/castes/nymph.dmi
  icons/Xeno/castes/panther.dmi
  icons/Xeno/castes/praetorian.dmi
  icons/Xeno/castes/predalien_larva.dmi
  icons/Xeno/castes/predalien_praetorian.dmi
  icons/Xeno/castes/predalien_warrior.dmi
  icons/Xeno/castes/queen.dmi
  icons/Xeno/castes/ravager.dmi
  icons/Xeno/castes/runner.dmi
  icons/Xeno/castes/scorpion.dmi
  icons/Xeno/castes/sentinel.dmi
  icons/Xeno/castes/shrike.dmi
  icons/Xeno/castes/spitter.dmi
  icons/Xeno/castes/warlock.dmi
  icons/Xeno/castes/warrior.dmi
Labels: Sprites, Cookie

#385 Fixes gib and dust animations.
  code/game/objects/effects/overlays.dm
  code/modules/mob/death.dm
  code/modules/mob/living/brain/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/predator/smartdisc.dm
Labels: Fix

#392 Автозаполнение кислотных колодцев
  code/modules/xenomorph/acidwell.dm
Labels: Xeno, Balance

#376 New icon
  icons/UI_Icons/map_blips_large.dmi
Labels: Sprites

#310 Shatters buff
  _maps/map_files/Talos/TGS_Talos.dmm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/effects/spawners/random/random_set.dm
  code/game/objects/effects/spawners/random/weaponry.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Marine, Balance

#393 Update actions_boiler_glob.dmi
  icons/Xeno/actions_boiler_glob.dmi
Labels: Removal, Sprites

#402 Acid well recharge rate
  code/modules/xenomorph/acidwell.dm
Labels: Xeno, Balance

#400 Acid well smoke is now transparent.
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/xenomorph/acidwell.dm
Labels: Fix, Xeno, Balance

#401 del sunder and sabot ammo
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
  code/modules/projectiles/ammo_datums/mecha.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/reqs/weapons.dm
Labels: Removal, Balance
