Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-08, with the labels that each got.

#61 Few fixes
  code/__DEFINES/loadout.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#62 Adds harvester holster
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#63 Update jobs.dm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/jobs.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/gamemode/crash_spawns.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Interface

#66 Adds blink icon back.
  icons/Xeno/actions.dmi
Labels: Fix, Sprites

#64 Отгружаю спрайты
  icons/RO_caps.dmi
  icons/RO_caps_onmob.dmi
  icons/RO_cloth_new.dmi
  icons/drill_cap.dmi
Labels: Sprites, Skill issue

#67 Medical twix
  code/__DEFINES/colors.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/movespeed_modification.dm
  code/game/data_huds.dm
  code/game/objects/items/devices/tweezers.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/food/drinks/drinkingglass.dm
  code/game/objects/items/reagent_containers/food/pizzapasta.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/food/soupsalad.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/mob/living/status_procs.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reactions/food_drink.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/drink.dm
  code/modules/reagents/reagents/food.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks.dm
Labels: Fix, Marine, Balance

#68 Fixes Talos window frames and also window and apc ex_acts.
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/modules/power/apc/apc.dm
Labels: Fix, Skill issue

#59 Factorio
  code/__DEFINES/_subsystems.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/points.dm
  code/controllers/subsystem/reqtorio.dm
  code/datums/gamemodes/_game_mode.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/factory/howtopaper.dm
  code/modules/factory/machines.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
  code/modules/reqtorio/assembly_crafts.dm
  code/modules/reqtorio/craft_components.dm
  code/modules/reqtorio/howtopaper.dm
  code/modules/reqtorio/machines.dm
  icons/obj/factory/factory_machines.dmi
  icons/obj/stack_objects.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/Assembler.js
Labels: Marine, Feature

#71 Recharger cell and cell tweaks.
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery/cell_charger.dm
  code/game/objects/machinery/recharger.dm
  code/modules/power/cell.dm
  code/modules/power/power.dm
  code/modules/projectiles/gun_system.dm
  tgmc.dme
Labels: Marine, Feature

#70 Fullscreen overlays and chat bullet act message cleanup
  code/_onclick/hud/fullscreen.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Optimization, Refactor

#69 Adds a stomach organ, pills, food and etc go into stomach and only then to blood.
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  code/__DEFINES/mobs.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/spawners/random/medical.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/portable_reagent_tank.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/supplypod.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
  code/modules/admin/verbs/podlauncher.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/brain/death.dm
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/_organ.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_alien.dm
  code/modules/organs/organ_internal.dm
  code/modules/organs/organ_objects.dm
  code/modules/organs/organ_props.dm
  code/modules/organs/organs.dm
  code/modules/predator/yautja/chems.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/reagents/drink.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/surgery/organs_internal.dm
  icons/obj/items/organs.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/CentcomPodLauncher.js
  tgui/packages/tgui/interfaces/MedScanner.js
  tgui/packages/tgui/interfaces/PodLauncher.js
Labels: Feature

#77 Tweaks talos cargo.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#74 Glasses cleanup and previous fuckups fixed.
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/clothing/eyes.dmi
  icons/mob/species/robot/glasses.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Refactor

#75 Delete prices and money interactions for vendors.
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Removal, QoL

#76 Locker qol and a little cleanup.
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/walllocker.dm
Labels: QoL

#79 Xeno wound and fire overlays now have `vis_inherit_id` flag
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#80 Makes railings on talos dense.
  code/game/objects/structures/prop.dm
Labels: Mapping, Feature

#81 Fixes fuel tank runtime.
  code/game/objects/structures/reagent_dispensers.dm
Labels: Fix

#82 Talos little tweaks.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#78 Storage qols
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/storage.dm
Labels: QoL

#85 Update lighting.dmi
  icons/obj/lighting.dmi
Labels: Sprites

#84 Restricts ground map vote from voting the current map.
  code/controllers/subsystem/vote.dm
Labels: Feature

#86 Xenos once again block marines diagonally.
  code/modules/mob/living/living.dm
Labels: Balance

#83 Ammo twix
  code/__DEFINES/conflict.dm
  code/__DEFINES/greyscale_guns.dm
  code/_globalvars/bitfields.dm
  code/datums/components/harvester.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
  code/modules/projectiles/ammo_datums/energy.dm
  code/modules/projectiles/ammo_datums/mecha.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/ammo_datums/rocket.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Marine, Balance, Feature

#87 Robot spawners
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/fallen.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/terragov.dm
  code/game/objects/effects/landmarks/gamemode/crash_spawns.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/landmarks.dmi
  tgui/packages/tgui/interfaces/LoadoutManager/index.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Fix

#88 Nerfs bihexajuline and inaprovaline ods
  code/modules/reagents/reagents/medical.dm
Labels: Marine, Balance

#90 Fixes resin move sounds.
  sound/effects/alien/resin_move1.ogg
  sound/effects/alien/resin_move2.ogg
  sound/effects/footstep/alien/resin_move1.ogg
  sound/effects/footstep/alien/resin_move2.ogg
Labels: Fix, Sound

#91 Restricts xenos from opening storages with items.
  code/game/objects/items/storage/storage.dm
Labels: Fix

#92 Optimizes explosion a bit.
  code/game/atoms/_atom.dm
  code/game/objects/effects/countdown.dm
  code/game/objects/effects/decals/turfdecals/markings.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/items.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/machinery/suit_storage_unit.dm
  code/game/objects/structures.dm
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/lamarr_cage.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/rocks.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/snow.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/hydroponics/vines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/apc/apc.dm
  code/modules/power/cable.dm
  code/modules/power/lighting.dm
  code/modules/power/terminal.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/recycling/disposal.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Optimization

#94 Attempt to prevent double explosion damage from explosion throws into explosion waves.
  code/__DEFINES/cooldowns.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Fix

#93 Changes smoothing groups of escape shuttle windows, so it doesn't smooth with ship walls.
  code/game/objects/structures/window.dm
Labels: Fix

#89 Fixes pipes on Talos.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#96 Medical pouches tweaks.
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
Labels: Fix, Balance

#98 Fixes that you could use radial medical menu to use non-present in-hand items on someone.
  code/game/objects/items/stacks/medical.dm
  code/modules/radial/radial_body_select.dm
Labels: Fix

#100 Defibrillator now heals oxy damage on the same formula as other damages.
  code/game/objects/items/defibrillator.dm
Labels: Balance

#102 Defiler tweaks and double attack signals sending fix.
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Labels: Fix, Balance

#104 Reverts lorians schizophreny.
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/resin.dm
Labels: QoL

#103 tyr & mimir
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Marine, Skill issue

#97 Новые турели #17
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/__DEFINES/loadout.dm
  code/__DEFINES/progress_display.dm
  code/datums/components/deployable_item.dm
  code/datums/looping_sounds/miscellaneous.dm
  code/datums/progressbar.dm
  code/game/objects/items.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/projectiles/sentries.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/sentry.dmi
  icons/effects/progressicons.dmi
  icons/mob/radial.dmi
  icons/obj/items/ammo.dmi
  sound/items/turrets/alarm_small.ogg
  sound/items/turrets/turret_breakdown.ogg
  sound/items/turrets/turret_fire.ogg
  sound/items/turrets/turret_idle_1.ogg
  sound/items/turrets/turret_idle_2.ogg
  sound/items/turrets/turret_lowammo.ogg
  sound/items/turrets/turret_noammo.ogg
  sound/items/turrets/turret_scan.ogg
  sound/items/turrets/turret_shotgun.ogg
  sound/items/turrets/turret_smg.ogg
  sound/items/turrets/turret_sniper.ogg
  sound/misc/electronics_1.ogg
Labels: Marine, Removal, Feature, Sprites

#99 Xeno walance
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Xeno, Balance

#107 Evolution now doesn't rely on caste, adds casteswap, adds strong acid for everyone on prep phase.
  code/__DEFINES/traits.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/misc.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Xeno, QoL, Feature

#105 rage rework
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Xeno, Balance

#109 Fixes gorger's feast
  code/datums/status_effects/xeno_buffs.dm
Labels: Fix, Xeno

#4 Points defence
  _maps/map_files/Xeno_den/Xeno_den.dmm
  code/__DEFINES/_radio.dm
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/minimap.dm
  code/__DEFINES/mode.dm
  code/_globalvars/game_modes.dm
  code/_globalvars/lists/objects.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/points_defence.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/telecomms/ground_telecomms.dm
  code/game/objects/machinery/telecomms/machines/relay.dm
  code/game/objects/structures/infestation_tower.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/screen_alert/misc_alert.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/tunnel.dm
  code/modules/xenomorph/xeno_core.dm
  icons/UI_Icons/map_blips.dmi
  icons/obj/structures/comm_tower2.dmi
  icons/obj/structures/sensor.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/MarineDropship.js
Labels: Mapping, Feature, Cookie

#101 extermination
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/extermination.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/xenomorph/silo.dm
  tgmc.dme
Labels: Feature

#110 Deletes widescreen.
  code/__DEFINES/preferences.dm
  code/controllers/configuration/entries/general.dm
  code/datums/view.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/login.dm
  code/modules/projectiles/attachables/scope.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/shuttle/mini_dropship.dm
  config/config.txt
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Removal

#112 Fixes misusage of `usr` in boomvest falling code.
  code/game/turfs/space/transit.dm
Labels: Fix

#111 Talos edit, remove guns, change sprite RO cap/uniform
  _maps/map_files/Talos/TGS_Talos.dmm
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/RO_caps_onmob.dmi
  icons/RO_cloth_new.dmi
  icons/drill_cap.dmi
  icons/mob/clothing/headwear/marine_hats.dmi
  icons/mob/clothing/headwear/marine_helmets.dmi
  icons/mob/clothing/uniforms/marine_uniforms.dmi
  icons/obj/clothing/headwear/RO_caps.dmi
  icons/obj/clothing/headwear/marine_hats.dmi
  icons/obj/clothing/headwear/marine_helmets.dmi
  icons/obj/clothing/uniforms/marine_uniforms.dmi
Labels: Mapping, Marine, Removal, Sprites, Skill issue

#106 Ifex + some twix
  code/game/data_huds.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reagents/reagents/medical.dm
  icons/mob/hud.dmi
Labels: Marine, Removal, Feature

#113 Talos some vend
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping, Marine

#114 Talos fixes.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#116 Fixes bypassing order limitations with keybinds.
  code/datums/actions/order_action.dm
  code/modules/screen_alert/command_alert.dm
Labels: Fix

#117 Fixes sprites of veteran uniform and shoes, also fixes separatist shoes.
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/obj/clothing/shoes.dmi
Labels: Fix, Sprites

#118 Fixes icons of handheld charger, advanced tweezers and alt optable.
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/OpTable.dm
  icons/obj/items/surgery_tools.dmi
Labels: Fix, Sprites

#119 Adds squad robot name specific settings. Fixes that you can't join as robot without squad chosen.
  code/datums/jobs/job/fallen.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/new_player/preferences_setup.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Labels: Fix, Feature

#120 Fix draw order not saving (#16128)
  code/modules/client/preferences_savefile.dm
Labels: Fix

#121 Readds warlock and hivemind to evolution pull.
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Fix

#123 swap_fix
  code/modules/mob/living/living.dm
Labels: Fix

#124 some chage TalOZ, tele in tank
  _maps/interiors/tank.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#125 pamphlet
  code/datums/jobs/job/shipside.dm
Labels: Fix

#128 pretty
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/interfaces/VehicleSupply.tsx
Labels: Interface

#130 Increases sanity of mob swapping checks.
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
Labels: Fix, Refactor

#131 Фиксы телепортации на танке
  code/game/atoms/atom_movable.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Fix

#132 I fix Ifex
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#133 Ravager buff
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance

#134 respawntime
  code/_globalvars/admin.dm
  code/datums/gamemodes/_game_mode.dm
Labels: Balance

#135 AssSembler fix
  code/__DEFINES/objects.dm
  code/modules/reqtorio/assembly_crafts.dm
  code/modules/reqtorio/craft_components.dm
  code/modules/reqtorio/machines.dm
Labels: Fix

#136 Radiopack fix
  code/modules/reqs/supply.dm
Labels: Fix

#137 Xenos now update hud on death.
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Fix

#138 Re-adds alt-rmb for storages, moves hypospray and pill bottle interaction to attackby.
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/storage.dm
Labels: Fix

#139 Swaps cargo prices of tweezers and advanced tweezers.
  code/modules/reqs/supplypacks.dm
Labels: Fix

#141 peridaxon fix
  code/modules/reagents/reagents/medical.dm
Labels: Fix, Skill issue

#142 Fixes zoom in formula.
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix, Skill issue

#145 фикс линтеров тгуи
  tgui/packages/tgui/interfaces/Assembler.js
  tgui/packages/tgui/interfaces/MarineDropship.js
  tgui/packages/tgui/interfaces/Mecha/MechStatPane.tsx
  tgui/packages/tgui/interfaces/VehicleSupply.tsx
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Fix

#144 Фикс танка 2
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#148 Deletes suicide verb and suicide_act.
  SQL/tgmc-schema.sql
  code/__DEFINES/span.dm
  code/controllers/subsystem/blackbox.dm
  code/datums/gamemodes/_game_mode.dm
  code/game/objects/items.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/verbs/suicide.dm
  code/modules/instruments/items.dm
  code/modules/mob/living/carbon/human/examine.dm
  tgmc.dme
Labels: Removal

#129 Remove removed revik, Koran fix, add GROZA in weapon vend
  code/__DEFINES/loadout.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/misc.dm
  code/game/objects/items/storage/bible.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Marine, Removal

#146 Slavanka 500
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/revolvers.dm
  icons/obj/items/ammo.dmi
Labels: Balance, Feature

#152 Boots buff
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Marine

#147 martini white
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/magazines/shotguns.dm
  icons/obj/items/ammo.dmi
Labels: Marine, Balance, Feature

#143 CAS Rebalance
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/dropship_equipment.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  icons/Marine/mainship_props.dmi
  icons/Marine/mainship_props64.dmi
  sound/weapons/bombdrop_sound.ogg
  sound/weapons/unguided_rocket.ogg
Labels: Removal, Balance, Feature, Sound, Sprites, Skill issue

#149 survivals
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/survivor.dm
  code/datums/skills.dm
  code/game/objects/items/radio/radio.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Marine, Balance, Feature

#154 Hunter
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Xeno, Balance

#157 Ability Cooldown Timers
  code/__DEFINES/action.dm
  code/datums/actions/ability_actions.dm
  code/game/objects/effects/countdown.dm
Labels: Port, QoL

#158 Resin hugger buff
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Xeno, Balance

#159 Pluto module
  code/__DEFINES/dcs/signals.dm
  code/datums/components/health_stealth.dm
  code/game/data_huds.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/style_line.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/modular/modular_armor_modules.dmi
  tgmc.dme
Labels: Marine, Feature

#160 new/old storage modules
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Marine, Feature

#161 Kills Regenerate Skin ability
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Labels: Removal, Xeno

#163 Fixes BE-35 and BE-47 night vision goggles.
  code/modules/clothing/glasses/night.dm
Labels: Fix

#150 Crafting qols.
  code/game/objects/items/stacks/stack.dm
Labels: Fix, QoL, Balance

#165 Praetorian toxin splash
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/castedatum_predalien.dm
  code/modules/projectiles/ammo_datums/xeno.dm
Labels: Fix, Xeno, Balance, Feature

#166 Fixes `handle_airdrop` not working for closets properly.
  code/game/turfs/space/transit.dm
Labels: Fix

#167 Lowers oblivion price from 1000 to 500.
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Xeno, Balance

#153 Some chems reb / fix
  code/modules/reagents/reagents/medical.dm
Labels: Fix, Marine, Balance, Feature

#155 Ravager Revork Episode 5: Ravager Strikes Back
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Xeno, Balance

#168 bone breake
  code/modules/reagents/reagents/medical.dm
Labels: Balance, Feature, Skill issue

#172 Fixes unmanned vehicles in valhalla adding to the ai controlled list.
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix

#170 Vendor coins
  code/__DEFINES/loadout.dm
  code/modules/reagents/reactions/medical.dm
Labels: Marine, Feature

#171 АИ-2 first aid kit for survs
  code/datums/jobs/job/survivor.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  icons/obj/items/storage/firstaidkit.dmi
Labels: Feature, Sprites

#140 Cleans up explosion code. Fixes admin pods.
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/_globalvars/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/remote_control.dm
  code/datums/fire_support.dm
  code/game/objects/effects/effect_system/effects_other.dm
  code/game/objects/explosion.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/misc.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/bots/roomba.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/supplypod.dm
  code/game/objects/structures/window.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/walls.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
  code/modules/admin/verbs/podlauncher.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/power/batteryrack.dm
  code/modules/power/lighting.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/ammo_datums/rocket.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/sentries.dm
  code/modules/reagents/reactions/other.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/motorbike.dm
  tgmc.dme
Labels: Optimization

#174 Fixes attachment handlers applying overlays while inhand.
  code/datums/components/attachment_handler.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/update_icons.dm
Labels: Fix

#179 Changed names and descriptions of credit coins.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/research.dm
  tgui/packages/tgui/interfaces/MarineSelector.js
Labels: Grammar and formatting

#180 Makes xeno ai's less suicidal.
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/presets/xeno_presets.dm
Labels: Feature

#182 up bike, nerf rmls in marinvend
  code/__DEFINES/loadout.dm
  code/datums/components/riding/riding_vehicle.dm
  code/game/objects/machinery/mortar.dm
Labels: Marine, Balance

#185 Fixes new jobs map blips.
  code/_globalvars/lists/flavor_misc.dm
  icons/UI_Icons/map_blips.dmi
Labels: Fix, Sprites

#187 Fixes rustg typo, minions now follow friendly player xenos if lost.
  code/__DEFINES/ai.dm
  code/__DEFINES/rust_g.dm
  code/__HELPERS/ai.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/ai_node.dm
Labels: Fix, Xeno, Feature

#164 Motorbike buff
  code/modules/vehicles/motorbike.dm
Labels: Marine, Balance

#186 Rav and Drone fixes
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Fix, Xeno, Balance

#184 Стандартные баррикады
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Mapping
