Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-11, with the labels that each got.

#607 Hivemind health hud fix.
  code/game/data_huds/xenomorph.dm
Labels: Fix

#595 Deletes gun greyscale configs and icons. Optimizes some random stuff a bit.
  code/__DEFINES/greyscale_guns.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/mapping.dm
  code/datums/greyscale/json_configs/attachments.json
  code/datums/greyscale/json_configs/attachments_64.json
  code/datums/greyscale/json_configs/gun.json
  code/datums/greyscale/json_configs/gun_fire.json
  code/datums/greyscale/json_configs/gun_hands.json
  code/datums/greyscale/json_configs/gun_mob.json
  code/datums/greyscale/json_configs/gun_revolver.json
  code/datums/greyscale/json_configs/gun_shotgun.json
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/projectiles/gun_system.dm
Labels: Removal, Optimization

#604 Fixes sprites of apc, fob button and some glasses. Also fixes opening time of hatch airlocks.
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/door.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/power/apc/apc.dm
  code/modules/power/apc/apc_appearance.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/machines/apc.dmi
  icons/obj/machines/buttons.dmi
Labels: Fix, Refactor, Sprites

#599 Attempt to fix secrete resin runtime.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#588 Ребаланс АГЛС-37
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/reqs/weapons.dm
Labels: Marine, Balance

#609 Acid unwell
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Xeno, Balance, Skill issue

#520 Adds adminhelp ban for admins.
  code/modules/admin/admin_verbs.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#587 Добавил тенглов марам
  code/__DEFINES/loadout.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/reqs/explosives.dm
  icons/mob/inhands/weapons/grenades_left.dmi
  icons/mob/inhands/weapons/grenades_right.dmi
  icons/obj/items/grenade.dmi
Labels: Marine, Balance, Feature

#593 Behemoth roll
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  icons/Xeno/castes/behemoth/basic.dmi
  icons/Xeno/castes/behemoth/effects.dmi
Labels: Xeno, Feature, Sprites

#542 Buff sg
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Marine, Balance

#620 Нерф ксеностенок
  code/game/turfs/walls/resin.dm
Labels: Xeno, Balance

#611 r76 и очередной ребаланс
  code/game/objects/items/storage/briefcase.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/reqs/weapons.dm
Labels: Marine, Balance

#605 Nerfs explosion throw.
  code/game/objects/explosion_recursive.dm
Labels: Balance, Stale

#621 Fixes laser pistol mode being semiauto while the pistol is fullauto.
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#617 Bullet feedback now properly checks for bullet damage.
  code/modules/projectiles/projectile.dm
Labels: Fix

#627 Fixes colored fire not working properly. Fixes xenomorph revive not reloading huds properly.
  code/datums/components/harvester.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/window.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/plating.dm
  code/modules/hydroponics/vines.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Fix

#629 You can now put materials into IS pattern storage module.
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Fix

#628 Proper telecomms for crash. Repaths telecomms.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/modularmaps/big_red/bigredcaveswvar2.dmm
  _maps/modularmaps/big_red/bigredcaveswvar3.dmm
  _maps/modularmaps/big_red/bigredcaveswvar4.dmm
  _maps/modularmaps/big_red/bigredcaveswvar5.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredsouthetavar1.dmm
  _maps/modularmaps/big_red/bigredsouthetavar4.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/telecomms/machines/allinone.dm
  code/game/objects/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/processor.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  tools/UpdatePaths/scripts/telecomms.txt
Labels: Fix, Mapping

#494 Tip of the Round, но по Русски
  strings/tips/HvH.txt
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/meta.txt
  strings/tips/xeno.txt
Labels: Skill issue, Grammar and formatting, Test Merge Candidate

#625 Удаление кишки лавового озера на Магмуре
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Mapping

#618 Бафф подствольного гранатомета
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Marine, Balance

#623 Нерф спрей-насадки
  code/modules/projectiles/attachables/flamer.dm
Labels: Marine, Balance

#632 Fixes wrong receiver type on Talos telecomms.
  _maps/map_files/Talos/TGS_Talos.dmm
  tools/UpdatePaths/scripts/telecomms.txt
Labels: Fix, Mapping

#636 Fixes unit tests failing on BigRed for real this time.
  code/game/area/bigred.dm
Labels: Fix, Mapping

#635 Tgas cargofix
  code/game/objects/items/storage/boxes.dm
  code/modules/reqs/explosives.dm
Labels: Fix

#630 Convert some `spawn()` to timers and asyncs.
  code/game/objects/items.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/spray.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/bioprinter.dm
  code/game/objects/machinery/camera/tracking.dm
  code/game/objects/machinery/computer/area_air_control.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/kitchen/smartfridge.dm
  code/game/objects/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets/fireaxe.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/turf.dm
  code/modules/animations/animation_library.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/economy/EFTPOS.dm
  code/modules/error_handler/error_handler.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/abilities_predalien.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/power/lighting.dm
  code/modules/power/smes_construction.dm
  code/modules/predator/smartdisc.dm
  code/modules/predator/yautja/bracers.dm
  code/modules/predator/yautja/weapons/ranged.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/recycling/disposal.dm
Labels: Optimization, Test Merge Candidate

#644 Fixes turned on lanterns, having turned off sprite.
  code/game/objects/items/flashlight.dm
Labels: Fix

#641 Adds empty back fueltanks sprites.
  icons/obj/items/ammo.dmi
Labels: Fix, Sprites

#639 Fixes connected ammo magazines not unloading from the gun on vendor restock.
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#640 Shoulder shooting now gives you shoot teammates if they are targeted.
  code/modules/projectiles/projectile.dm
Labels: Fix

#637 Offhand layer is lower than item layer.
  code/datums/elements/riding.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/inventory.dm
Labels: Feature

#648 Cargo optimization!
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/reqs/_supplypacks.dm
  code/modules/reqs/imports.dm
  code/modules/reqs/launchers.dm
  code/modules/reqs/operations.dm
  code/modules/reqs/smartguns.dm
  code/modules/reqs/stationary.dm
  code/modules/reqs/supplies.dm
  code/modules/reqs/vehicles.dm
  code/modules/reqs/weapons.dm
  icons/obj/structures/crates.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: QoL, Sprites

#650 Squad Leader now needs either marine exp, or command exp to play.
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
Labels: Feature

#645 jetpackWithoutStagger
  code/game/objects/items/jetpack.dm
Labels: Marine, Balance

#591 Rebalance ammo
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
Labels: Balance, Test Merge Candidate

#594 Rebalance xeno HP and armor
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Labels: Xeno, Balance, Test Merge Candidate

#614 Ксенодверям надо 2 тайла между собой для постройки
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Xeno, Balance

#619 Перевод разделов, возвращение лазерганов, перенос ряда пушек в разделы
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Marine, Balance, Grammar and formatting

#660 M344 belt and pistol belt buff
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/loadout.dm
  code/datums/components/easy_restock.dm
  code/datums/components/magazine_catcher.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/reqs/clothing.dm
  icons/obj/clothing/belts.dmi
  tgmc.dme
Labels: Marine, Feature

#659 Fixes carrier hugger overlays not applying correctly.
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
Labels: Fix

#626 Adds sticky acid grenade for primordial spitter. Also now has strong acid.
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Labels: Balance, Feature

#624 Шляпы теперь зависят от одного и того же дефайна
  code/modules/clothing/head/head.dm
Labels: Marine, Balance

#597 Rework some attachments, give mg60 aim mode and add all attach AR
  code/modules/projectiles/attachables/foldable.dm
  code/modules/projectiles/attachables/muzzle.dm
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/attachables/scope.dm
  code/modules/projectiles/attachables/underbarrel.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Marine, Balance, Test Merge Candidate

#642 Изменение иконок приказов
  icons/mob/actions.dmi
  icons/mob/order_icons.dmi
Labels: Marine, Sprites

#643 Новый спрайт БТРа
  icons/obj/armored/3x3/apc.dmi
  icons/obj/armored/3x3/apc_damage_overlay.dmi
Labels: Marine, Sprites

#665 Фикс отсутствия паверфиста на дистрессе
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix, Marine

#651 Handheld Charger and MRE for Cargo.
  code/modules/reqs/engineering.dm
  code/modules/reqs/supplies.dm
Labels: Feature

#656 Merge join and ready button.
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/controllers/subsystem/ticker.dm
  icons/UI_Icons/lobby_button.dmi
Labels: QoL

#674 Field researcher
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Balance

#657 Replaces `spawn()` in explosion code to `addtimer` and `INVOKE_ASYNC`.
  code/game/objects/effects/decals/decal.dm
  code/game/objects/effects/decals/turfdecals/markings.dm
  code/game/objects/effects/effect.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/structures/supplypod.dm
Labels: Optimization, Test Merge Candidate

#683 Swat mask now tears apart, after facehugger attach attempt.
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  icons/mob/clothing/mask.dmi
  icons/obj/clothing/masks.dmi
  sound/items/velpro_rip.ogg
Labels: Feature

#658 Carrier buff
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Xeno, Balance, Test Merge Candidate

#633 Add carrier changes
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
Labels: Xeno, Balance, Feature

#586 Widow
  code/__DEFINES/action.dm
  code/__DEFINES/actions.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/datums/actions/ability_actions.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/widow.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums/xeno.dm
  html/changelogs/archive/2024-10.yml
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/Effects.dmi
  icons/Xeno/actions.dmi
  icons/Xeno/castes/widow/basic.dmi
  icons/Xeno/castes/widow/effects.dmi
  icons/obj/items/projectiles.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Xeno, Balance, Feature

#638 Сhanges the amount of marines required to block hijack.
  code/datums/gamemodes/_game_mode.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Balance, Test Merge Candidate

#687 Нерф флаеров
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance

#634 Adds beginner loadout vendor.
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/equipment.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/_globalvars/bitfields.dm
  code/datums/outfit.dm
  code/datums/quick_load/_quick_load.dm
  code/datums/quick_load/beginner/_beginner.dm
  code/datums/quick_load/beginner/corpsman.dm
  code/datums/quick_load/beginner/engineer.dm
  code/datums/quick_load/beginner/marine.dm
  code/datums/quick_load/beginner/robot.dm
  code/datums/quick_load/beginner/smartgunner.dm
  code/datums/quick_load/som/_som.dm
  code/datums/quick_load/som/engineer.dm
  code/datums/quick_load/som/leader.dm
  code/datums/quick_load/som/marine.dm
  code/datums/quick_load/som/medic.dm
  code/datums/quick_load/som/veteran.dm
  code/datums/quick_load/tgmc/_tgmc.dm
  code/datums/quick_load/tgmc/corpsman.dm
  code/datums/quick_load/tgmc/engineer.dm
  code/datums/quick_load/tgmc/leader.dm
  code/datums/quick_load/tgmc/marine.dm
  code/datums/quick_load/tgmc/smartgunner.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/machinery/vending/beginner_vendor.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/paperwork/beginner_tutorials.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/energy.dm
  icons/obj/machines/vending.dmi
  tgmc.dme
Labels: Feature, Test Merge Candidate

#690 Spiderling HP 225 -> 150
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
Labels: Xeno, Balance

#695 Коробки с патронами на скаутскую винтовку.
  code/modules/projectiles/magazines/misc.dm
  code/modules/reqs/weapons.dm
Labels: Feature

#705 Fixes jump to area verb.
  code/modules/admin/admin_verbs.dm
Labels: Fix

#691 Changes default jumping keybind from Space to V.
  code/datums/keybinding/living.dm
Labels: QoL

#698 Fixes boosty button theme. Some adjucements to interface buttons.
  interface/interface.dm
  interface/skin.dmf
  tgui/packages/tgui-panel/themes.ts
Labels: Fix

#696 Removes AA from clown.
  code/datums/jobs/job/clown.dm
Labels: Removal

#697 Adds directional sprites for windows.
  code/game/objects/structures/mirror.dm
  icons/obj/watercloset.dmi
Labels: Sprites

#708 Fixes reqtorio crafts that use glass not accepting it as a input.
  code/modules/reqtorio/assembly_crafts.dm
Labels: Fix

#693 Buffs sg29.
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Marine, Balance

#702 Tweak oxycodone
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#654 Steel crest
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/living.dm
  icons/Xeno/actions.dmi
  icons/Xeno/castes/defender/steel_crest.dmi
Labels: Xeno, Feature

#692 Adds keycard authenticators to command rooms.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#671 SG-85 goes BRRR
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Balance, Test Merge Candidate

#707 Removes evolution fade in. Xeno ruler announcement is now correct. Some experimental tweaks.
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix, Removal

#710 Deletes free cargo ammunition from cargo vendor's "Surplus Special Equipment" tab
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal

#689 Ports action code improvements.
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/overwatch.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/actions/action.dm
  code/datums/actions/innate.dm
  code/datums/actions/item_action.dm
  code/datums/actions/item_toggles.dm
  code/datums/actions/order_action.dm
  code/datums/actions/skill.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/militarypolice.dm
  code/datums/jobs/job/other.dm
  code/datums/jobs/squads.dm
  code/datums/outfit.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/projectiles/attachables/foldable.dm
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/attachables/underbarrel.dm
  code/modules/projectiles/gun_system.dm
  code/modules/screen_alert/command_alert.dm
Labels: Port, Optimization, Test Merge Candidate

#670 Mimir great again V2
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/reqs/armor.dm
  code/modules/xenomorph/acidwell.dm
Labels: Balance

#712 Fix King ability "Petrify"
  code/datums/components/deployable_item.dm
Labels: Fix

#718 Xeno leader death timer fix (#15868)
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix, Port

#713 HiveMind fix acid trail
  code/datums/status_effects/xeno_buffs.dm
Labels: Fix

#704 Ammo.dmi reorganization.
  code/__DEFINES/calibers.dm
  code/__DEFINES/greyscale_guns.dm
  code/datums/greyscale/greyscale_configs.dm
  code/game/objects/items/rcd.dm
  code/modules/projectiles/ammo_casing.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/big_ammo_box.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/handful.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/projectiles/magazines/unmanned_vehicle.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/ammo/box.dmi
  icons/obj/items/ammo/energy.dmi
  icons/obj/items/ammo/flamer.dmi
  icons/obj/items/ammo/handful.dmi
  icons/obj/items/ammo/magazine.dmi
  icons/obj/items/ammo/misc.dmi
  icons/obj/items/ammo/packet.dmi
  icons/obj/items/ammo/pistol.dmi
  icons/obj/items/ammo/revolver.dmi
  icons/obj/items/ammo/rocket.dmi
  icons/obj/items/ammo/smg.dmi
  icons/obj/items/ammo/stationary.dmi
  icons/obj/items/ammo/tank.dmi
  tgmc.dme
Labels: Sprites, Test Merge Candidate
