Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-12, with the labels that each got.

#721 prime>primal
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Grammar and formatting

#729 Defib rechargers
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping

#726 Хайвмайнд понимает маров
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Feature

#728 Gives king sledge inmunity
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance

#724 Getflaticon optimisation
  code/__HELPERS/icons.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/icons.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_helpers.dm
  tgmc.dme
Labels: Port, Code Improvement

#723 Adds a special do_after display for unequipping facehuggers.
  code/__DEFINES/progress_display.dm
  code/datums/elements/strippable.dm
  code/datums/progressbar.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/silicon/silicon.dm
  icons/effects/progressicons.dmi
Labels: QoL

#711 Xeno turrets now scan surroundings every tick. Buffs hugger turret. Sentient facehugger from hugger turret.
  code/__DEFINES/objects.dm
  code/__DEFINES/xeno.dm
  code/__HELPERS/ai.dm
  code/_onclick/ai.dm
  code/datums/actions/observer_action.dm
  code/datums/gamemodes/infestation.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/projectiles/ammo_datums/xeno.dm
  code/modules/xenomorph/turret.dm
  icons/Xeno/acidturret.dmi
Labels: Refactor, Xeno, Balance, Sprites

#732 Species.dm and emote.dm cleaning up.
  code/datums/actions/species_actions/robot_action.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/emote/human.dm
  code/modules/mob/living/carbon/human/emote/necoarc.dm
  code/modules/mob/living/carbon/human/emote/robot.dm
  code/modules/mob/living/carbon/human/emote/yautja.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/carbon/human/logout.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/mob/living/carbon/human/species/early_synthetic.dm
  code/modules/mob/living/carbon/human/species/hud_data.dm
  code/modules/mob/living/carbon/human/species/human.dm
  code/modules/mob/living/carbon/human/species/monkey.dm
  code/modules/mob/living/carbon/human/species/moth.dm
  code/modules/mob/living/carbon/human/species/necoarc.dm
  code/modules/mob/living/carbon/human/species/robot.dm
  code/modules/mob/living/carbon/human/species/sectoid.dm
  code/modules/mob/living/carbon/human/species/skeleton.dm
  code/modules/mob/living/carbon/human/species/synthetic.dm
  code/modules/mob/living/carbon/human/species/unarmed_attack.dm
  code/modules/mob/living/carbon/human/species/vatborn.dm
  code/modules/mob/living/carbon/human/species/vatgrown.dm
  code/modules/mob/living/carbon/human/species/yautja.dm
  code/modules/mob/living/carbon/human/yautja.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/update_icons.dm
  tgmc.dme
Labels: Code Improvement

#675 Mutation qol
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Xeno, QoL, Balance

#736 Fixes selling humans now giving any points. Fixes statistics error.
  code/modules/requisitions/supply_export.dm
Labels: Fix

#739 widow bugfix
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Labels: Fix

#734 Kutjevo adjustments and fixes.
  _maps/map_files/kutjevo/kutjevo.dmm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  icons/obj/smooth_objects/kutjevo_window_blue.dmi
  icons/obj/smooth_objects/kutjevo_window_blue_reinforced.dmi
  icons/obj/smooth_objects/kutjevo_window_frame.dmi
  icons/obj/smooth_objects/kutjevo_window_frame_reinforced.dmi
  icons/obj/smooth_objects/kutjevo_window_orange.dmi
  icons/obj/smooth_objects/kutjevo_window_orange_reinforced.dmi
  icons/turf/floors/river_desert.dmi
Labels: Fix, Mapping, Sprites

#748 Predlarva can now evolve to predalien.
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
Labels: Fix

#747 Fixes tank being able to shoot 1 extra time.
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Fix

#700 Кейбинды без конфликтов (ксено)
  code/datums/keybinding/xeno.dm
Labels: QoL

#731 Decreseases fumbling time for shrapnel removal in 2 times.
  code/datums/elements/shrapnel_removal.dm
Labels: Balance

#738 Переозвучка B18 + мини-добавление
  code/datums/elements/limb_support.dm
  sound/voice/b18/activate.ogg
  sound/voice/b18/antitoxin.ogg
  sound/voice/b18/antitoxin2.ogg
  sound/voice/b18/brute.ogg
  sound/voice/b18/diying.ogg
  sound/voice/b18/fracture.ogg
  sound/voice/b18/ib_detected.ogg
  sound/voice/b18/light_fracture.ogg
  sound/voice/b18/pain_suppress.ogg
  sound/voice/b18/tox.ogg
Labels: Sound

#746 Gives hunter vampirism
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Xeno, Balance

#740 Нерф СР 127
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/effects/spawners/random/random_set.dm
  code/game/objects/effects/spawners/random/weaponry.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#761 Acid blood is now exclusive to the sentinel branch, and queen
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/chimera/castedatum_chimera.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hellhound/hellhound.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance

#744 Vindicator minigun nerf
  code/__DEFINES/supply.dm
Labels: Marine, Balance

#742 A possible FPS lag fix caused by chat spam (port)
  tgui/packages/tgui-panel/chat/renderer.jsx
Labels: Port, Code Improvement, Test Merge Candidate

#757 Fixes join button runtime.
  code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Fix

#733 Завод теперь может производить снаряды для ФК88 и танковые снаряды для главного орудия
  code/modules/reqtorio/assembly_crafts.dm
  code/modules/vehicles/armored/ammo_magazine.dm
Labels: Feature, Grammar and formatting

#749 Strains buff
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/projectiles/ammo_datums/xeno.dm
Labels: Xeno, Balance

#716 Повышение капа реагентов с фреером до 10 вместо 8
  code/modules/organs/organs.dm
Labels: Balance

#754 Panther buff
  code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
Labels: Balance

#612 Убрал аим и прицелы у двушки, рельсы и всех лазганов кроме лазснайпы
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Marine, Balance

#764 Port fix auto Fit Viewport
  code/datums/view.dm
  code/game/verbs/ooc.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
Labels: Port, Code Improvement

#766 Фаллов Вектор 3 >> 1.75, убрал дубликаты кода allowed_ammo_types
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Marine, Code Improvement, Balance

#765 Nerf MK88
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Marine, Balance

#772 Add to P-17 the underbarrel-flashlight
  code/modules/projectiles/guns/pistols.dm
Labels: Balance

#780 Fix tank chair wrench
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/vehicles/armored/interiors/chairs.dm
Labels: Fix

#784 Reagent scanner icon fix
  code/game/objects/items/scanners.dm
Labels: Fix

#783 Old alt+rightclick (take left object from storage)
  code/game/objects/items/storage/storage.dm
Labels: QoL

#785 Changes RL-160 rocket size.
  code/modules/projectiles/magazines/specialist.dm
Labels: Balance

#727 Crash tweaks
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/datums/gamemodes/crash.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/computer.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/xeno_towers.dm
Labels: Removal, Balance, Feature

#778 Лютый фикс лампочки в меде
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#686 Toggleable auto-catch and easy restock for revolvers
  code/datums/components/magazine_catcher.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Feature

#782 Storage close fix
  code/game/objects/items/storage/storage.dm
Labels: Fix

#790 Hugger statistics
  code/datums/elements/strippable.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/surgery/organs_internal.dm
Labels: Feature

#769 Port parallax
  code/__DEFINES/preferences.dm
  code/_onclick/hud/parallax.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/shuttle/on_move.dm
Labels: Port, Code Improvement

#767 Removes iff from b7 scope, removes aim mode from scopes.
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/attachables/scope.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Marine, Removal

#786 Change FK88 ammo cost in factory and add granade launcher ammo
  code/modules/reqs/supplypacks/vehicles.dm
  code/modules/reqtorio/assembly_crafts.dm
Labels: Balance, Feature

#802 Кодекс огнестрела 2.0
  code/modules/codex/entries/guns_codex.dm
Labels: QoL

#762 Xeno upgrades nerf
  code/__DEFINES/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/objects/structures/xeno/resin.dm
Labels: Balance

#610 New speedboost reagent for marines MasTac
  code/__DEFINES/colors.dm
  code/__DEFINES/loadout.dm
  code/game/data_huds/human.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reagents/reactions/other.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks/medical.dm
  icons/mob/hud/reagent.dmi
Labels: Marine, Feature

#706 PTRD
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/mounted.dm
  code/modules/reqs/supplypacks/imports.dm
Labels: Balance, Feature

#805 Fixes runner pounce not unregistering delete signal properly.
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#807 Fixes armored vehicle crew bunk vents not leading anywhere.
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Fix, Mapping

#770 Now crate can be pulled out of the APC.
  code/__DEFINES/is_helpers.dm
  code/datums/interior/interior_tank.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Fix

#814 Лютый фикс спрайта коробки с Уно
  code/game/objects/items/toys/cards.dm
Labels: Fix

#815 Fixes runtimes with explosion sounds, lobby join button and warrior jab punch.
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/datums/autocells/explosion.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#699 Praetorian dancer strain
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/actions.dmi
  icons/Xeno/castes/praetorian/dancer.dmi
Labels: Xeno, Feature

#820 Fixes v21 not having ammo band sprite.
  icons/obj/items/ammo/smg.dmi
Labels: Fix, Sprites

#788 Гойдафикация денег
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/lv624/internal_affairs.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar7.dmm
  code/datums/gamemodes/objective.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/machinery/computer/arcade.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/economy/cash.dm
  code/modules/reqs/supplypacks/supplies.dm
  icons/obj/stack_objects.dmi
Labels: Fix, Feature, Sprites

#745 Tank nerf
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Marine, Balance, Test Merge Candidate

#817 Storage can be open on click with too big item
  code/game/objects/items/storage/storage.dm
Labels: Fix

#750 Bumps up qdel, garbage cleaning and MC from TG.
  code/__DEFINES/rust_g.dm
  code/__HELPERS/icons.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/icon_smooth.dm
  code/controllers/subsystem/timer.dm
  code/datums/datum.dm
  code/game/objects/machinery/computer/camera.dm
  code/game/objects/objs.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/mapping/reader.dm
  code/modules/mob/mob.dm
  code/modules/predator/yautja/bracers.dm
  code/modules/projectiles/attachables/_attachable.dm
  code/modules/projectiles/gun_system.dm
  code/modules/reqs/ui/vehicle.dm
  code/modules/tgs/v3210/api.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/find_reference_sanity.dm
  code/modules/vehicles/armored/interiors/chairs.dm
  code/modules/xenomorph/xeno_towers.dm
Labels: Port, Code Improvement, Test Merge Candidate

#804 Plasma cutter fixes
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/tools.dm
  code/_onclick/item_attack.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/objs.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/resin.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/xenomorph/_xeno_structure.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/turret.dm
Labels: Fix, Balance

#827 Assault crewman can't controll mech
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/game/objects/items/pamphlets.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Labels: Fix

#821 Hunter blink change
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix

#796 DMR fire mods
  code/modules/projectiles/guns/rifles.dm
Labels: Marine

#833 В Коран теперь можно ложить small вещи
  code/game/objects/items/misc.dm
Labels: Feature

#836 Tweak/nerf Alkyzine
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks/medical.dm
Labels: Balance

#837 Adds codex for CAS rockets
  code/modules/codex/entries/cas_ammo_codex.dm
  tgmc.dme
Labels: QoL

#832 Deletes Mastac (NeuroFrenzy)
  code/__DEFINES/colors.dm
  code/__DEFINES/loadout.dm
  code/game/data_huds/human.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reagents/reactions/other.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks/medical.dm
Labels: Removal, Skill issue

#824 Quick build work until TAD lands off the LZ.
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/processing/resinshaping.dm
  code/controllers/subsystem/silo.dm
  code/game/area/kutjevo.dm
  code/game/objects/structures/droppod.dm
  code/modules/condor/cas_chair.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/shuttle/mini_dropship.dm
Labels: Feature

#845 Fixes nutriment `on_merge` runtime.
  code/modules/reagents/reagents/food.dm
Labels: Fix

#844 Increases shrike plasma regeneration from 45 to 55.
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Xeno, Balance

#842 Больше модулей на Нигредо
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Balance

#799 Musket return
  code/__DEFINES/calibers.dm
  code/datums/jobs/job/shipside.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/Marine/gun64.dmi
  icons/mob/clothing/back.dmi
  icons/mob/hud/ammo.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo/handful.dmi
  icons/obj/items/ammo/packet.dmi
Labels: Feature

#848 Roadmap - Vali rapir delete skill lock
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance, Feature

#774 Альбедо и Нигредо 2: Медицинский револьвер (дубль 2)
  code/__DEFINES/calibers.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/loadout.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks/medical.dm
  icons/Marine/marine-pouches.dmi
  icons/mob/hud/ammo.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo/handful.dmi
  icons/obj/items/ammo/packet.dmi
  icons/obj/items/ammo/revolver.dmi
  sound/weapons/guns/fire/t312.ogg
Labels: Balance, Feature, Test Merge Candidate

#849 Adds amount restriction for vending. Increases plushies cargo price. Squeak component improvements. Items now properly remove from storages on being cryoed.
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/components/squeak.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/vending/vending.dm
  code/modules/reqs/supplypacks/supplies.dm
Labels: Fix, Code Improvement, Balance, Feature

#846 Gorger changes (вторая попытка)
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  icons/effects/96x96.dmi
Labels: Balance, Feature

#856 Port strapable fixes
  code/datums/elements/strappable.dm
  code/modules/mob/mob.dm
Labels: Fix

#840 Психический щит: Направленное отражение (Колдун Примо)
  code/datums/personal_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Feature

#857 Researcher implant minor upgrade
  code/game/objects/items/implants/implant_cloak.dm
  code/game/objects/items/implants/implant_items.dm
  code/game/objects/machinery/research.dm
Labels: Balance

#863 Укреплённый пол больше не удаляет пол до базового тюрфа
  code/game/objects/items/stacks/rods.dm
Labels: Fix

#864 `status_procs.dm` cleaning.
  code/__DEFINES/mobs.dm
  code/datums/actions/ability_actions.dm
  code/datums/components/shield.dm
  code/datums/components/stun_mitigation.dm
  code/datums/status_effects/status_effect.dm
  code/game/data_huds/human.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/living/status_procs/blindness.dm
  code/modules/mob/living/status_procs/blur.dm
  code/modules/mob/living/status_procs/confused.dm
  code/modules/mob/living/status_procs/dizzy.dm
  code/modules/mob/living/status_procs/drugginess.dm
  code/modules/mob/living/status_procs/ear_damage.dm
  code/modules/mob/living/status_procs/immobilize.dm
  code/modules/mob/living/status_procs/irradiated.dm
  code/modules/mob/living/status_procs/jitter.dm
  code/modules/mob/living/status_procs/knockdown.dm
  code/modules/mob/living/status_procs/mute.dm
  code/modules/mob/living/status_procs/paralyze.dm
  code/modules/mob/living/status_procs/sleeping.dm
  code/modules/mob/living/status_procs/slowdown.dm
  code/modules/mob/living/status_procs/stagger.dm
  code/modules/mob/living/status_procs/stun.dm
  code/modules/mob/living/status_procs/stun_absorption.dm
  code/modules/mob/living/status_procs/temperature.dm
  code/modules/mob/living/status_procs/unconscious.dm
  code/modules/mob/mob_movement.dm
  code/modules/predator/falcon.dm
  code/modules/predator/predator_action.dm
  code/modules/predator/thrall/procs.dm
  code/modules/predator/yautja/bracers.dm
  code/modules/predator/yautja/hudprocs.dm
  code/modules/predator/yautja/items.dm
  code/modules/predator/yautja/procs.dm
  code/modules/projectiles/ammo_datums/_ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/recycling/disposal.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  tgmc.dme
Labels: Code Improvement

#862 Slightly improves cinematics code.
  code/datums/cinematic.dm
  code/datums/gamemodes/infestation.dm
Labels: Code Improvement

#859 Adds more medical equipment to medical APC interior.
  _maps/interiors/apc_medical.dmm
Labels: Feature

#861 Техника клонирования
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
Labels: Fix

#852 Russian Red no more in marin vendor
  code/__DEFINES/loadout.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/reqs/supplypacks/medical.dm
Labels: Balance, Test Merge Candidate

#870 Old gun firemode verb deletion and some keybind unshittening (#16543)
  code/datums/actions/item_action.dm
  code/datums/components/deployable_item.dm
  code/modules/projectiles/attachables/_attachable.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix, Port

#876 Синты и ИИ теперь могут писать ключ бинарного канала на русском
  code/modules/mob/living/say.dm
Labels: QoL

#865 Deletes station mechs and mech stuff.
  _maps/map_files/deltastation/deltastation.dmm
  code/__DEFINES/mecha.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/combat.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/marauder.dm
  code/modules/vehicles/mecha/combat/phazon.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  code/modules/vehicles/mecha/equipment/tools/work_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/mecha/greyscale/greyscale.dm
  code/modules/vehicles/mecha/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/mech_bay.dm
  code/modules/vehicles/mecha/mech_melee_attack.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/mecha/mecha_helpers.dm
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
  code/modules/vehicles/mecha/mecha_movement.dm
  code/modules/vehicles/mecha/mecha_ui.dm
  code/modules/vehicles/mecha/working/ripley.dm
  code/modules/vehicles/mecha/working/working.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Mecha/MaintMode.tsx
  tgui/packages/tgui/interfaces/Mecha/MechStatPane.tsx
  tgui/packages/tgui/interfaces/Mecha/OperatorMode.tsx
  tgui/packages/tgui/interfaces/Mecha/PowerModulesPane.tsx
  tgui/packages/tgui/interfaces/Mecha/data.ts
  tgui/packages/tgui/interfaces/Mecha/index.tsx
Labels: Removal

#858 New tad "Barge"
  _maps/shuttles/minidropship_barge.dmm
  code/datums/shuttles.dm
  code/game/objects/machinery/computer/dropship_picker.dm
  icons/UI_Icons/dropshippicker/_barge.png
Labels: Feature

#877 Warding Pheromones rework
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/mob/living/carbon/pain.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance

#880 Void Raider New Tad
  _maps/shuttles/minidropship_voidraider.dmm
  code/datums/shuttles.dm
  code/game/objects/machinery/computer/dropship_picker.dm
  icons/UI_Icons/dropshippicker/_voidraider.png
Labels: Mapping, Feature
