Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2024-07, with the labels that each got.

#9 Adds predalien to mob list.
  code/_globalvars/lists/mobs.dm
Labels: Xeno, QoL

#7 Nightfall extuinguishes active flares.
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Xeno, Balance

#10 Space transit tiles now send atoms flying to the ground.
  code/game/objects/items/explosives/bombvest.dm
  code/game/sound.dm
  code/game/turfs/space.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/modules/organs/limbs.dm
Labels: Marine, Xeno, Feature

#12 Increasing energy consumption from ship rods
  code/modules/power/fusion_engine.dm
Labels: Marine, Balance

#13 Makes hunter mirages more convincing, motion detectors now ignore xenos in stealth, adds some ap to hunter's stealth attacks.
  code/__HELPERS/ai.dm
  code/_globalvars/lists/mobs.dm
  code/game/objects/items/motion_detector.dm
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/projectiles/sentries.dm
Labels: Fix, Marine, Xeno, Balance

#14 Return of the tur, change in the status of modules and armor, new type of armor
  code/__DEFINES/loadout.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Marine, Refactor, Balance, Feature

#22 Xeno penetration
  code/modules/codex/entries/ammunition_codex.dm
  code/modules/codex/entries/magazine_codex.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Marine, Xeno, Feature

#24 Off-hand shooting
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/mounted.dm
Labels: Port, Marine, Feature

#27 Storage opening QOL
  code/game/objects/items/storage/storage.dm
Labels: Port, QoL

#28 Makes the radial menu for all medicine fit all limbs.
  code/_onclick/hud/radial.dm
  code/modules/radial/radial_body_select.dm
Labels: Port, QoL

#29 Storage closing QOL
  code/game/objects/items/storage/storage.dm
Labels: Port, QoL

#30 Directional attack
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/_onclick/click.dm
  code/datums/elements/directional_attack.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/living.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Balance, Feature

#25 Medical items now apply to yourself if you use them in-hand
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/stacks/medical.dm
Labels: Port, QoL

#31 Few fixes to the sky diving.
  code/game/turfs/space/transit.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#20 Marine vending
  code/__DEFINES/loadout.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/obj/machines/vending.dmi
Labels: Marine, Feature

#40 Фикс очепятки.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Fix

#35 Reorgs `xeno_structures.dm`, tunnels now use minimap to choose exit.
  code/__HELPERS/ai.dm
  code/modules/xenomorph/_xeno_structure.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/jellypod.dm
  code/modules/xenomorph/nest.dm
  code/modules/xenomorph/plant.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
  code/modules/xenomorph/trap.dm
  code/modules/xenomorph/tunnel.dm
  code/modules/xenomorph/turret.dm
  code/modules/xenomorph/xeno_structures.dm
  code/modules/xenomorph/xeno_towers.dm
  tgmc.dme
Labels: Xeno, Feature

#37 Deletes mech duplicate files.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredofficevar1.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/lv624/newcavevar2.dmm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/modules/vehicles/mecha/mech_bay.dm
  code/modules/vehicles/mecha/mecha_parts.dm
  code/modules/vehicles/mecha/mecha_wreckage.dm
  tgmc.dme
Labels: Refactor

#39 Refactors and resprites robotic cradle.
  code/game/objects/machinery/robotic_cradle.dm
  icons/obj/machines/robotic_cradle.dmi
  tgmc.dme
Labels: Fix, Refactor, QoL, Balance, Sprites

#42 Ports 14878, 15112, 15167
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/predator/yautja/weapons/ranged.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix, Optimization, Refactor

#8 New and changed corps equipment
  code/__DEFINES/loadout.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/reqs/supplypacks.dm
Labels: Marine, Balance, Feature

#43 Guns, attachables and ammo cleanup.
  code/datums/greyscale/greyscale_configs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_datums/_ammo_datums.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/ammo_datums/bullet/_bullet.dm
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/revolver.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
  code/modules/projectiles/ammo_datums/energy.dm
  code/modules/projectiles/ammo_datums/flamethrower.dm
  code/modules/projectiles/ammo_datums/mecha.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/ammo_datums/rocket.dm
  code/modules/projectiles/ammo_datums/shrapnel.dm
  code/modules/projectiles/ammo_datums/xeno.dm
  code/modules/projectiles/ammo_datums/yautja.dm
  code/modules/projectiles/attachables/_attachable.dm
  code/modules/projectiles/attachables/flamer.dm
  code/modules/projectiles/attachables/foldable.dm
  code/modules/projectiles/attachables/muzzle.dm
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/attachables/scope.dm
  code/modules/projectiles/attachables/stock.dm
  code/modules/projectiles/attachables/underbarrel.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  tgmc.dme
Labels: Removal, Optimization

#44 Aim mode
  code/datums/actions/item_action.dm
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Marine, Removal, Balance

#46 Deletes unused hostile simple mobs, deletes old cyborg gear.
  _maps/map_files/LV624/LV624.dmm
  code/__DEFINES/cooldowns.dm
  code/game/area/general.dm
  code/game/objects/effects/spawners/random/engineering.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/tools/mining_tools.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/constructs.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  icons/effects/effects.dmi
  icons/mob/animal.dmi
  icons/mob/hivebot.dmi
  icons/mob/simple_human.dmi
  tgmc.dme
Labels: Removal

#45 Combat robot
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/jobs/job/fallen.dm
  code/datums/jobs/job/marines.dm
  code/datums/outfit.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/hud.dmi
  icons/obj/machines/vending.dmi
  tgmc.dme
Labels: Marine

#47 Movement fixes and adjustments.
  code/datums/components/bump_attack.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
Labels: Fix, Refactor, Xeno, Feature

#21 Cargo fast delivery
  code/controllers/subsystem/points.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supply.dm
  tgui/packages/tgui/interfaces/Cargo.js
Labels: Marine, QoL, Feature, Interface

#51 Aim mode 2
  code/datums/actions/item_action.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/attachables/rail.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/marine-weapons.dmi
Labels: Marine, Feature

#48 Resting rework.
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mobs.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/keybinding/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_verbs.dm
Labels: Xeno, QoL

#53 Req qols.
  code/__DEFINES/obj_flags.dm
  code/modules/reqs/supply.dm
  icons/UI_Icons/map_blips.dmi
  tgui/packages/tgui/interfaces/Cargo.js
Labels: QoL

#52 Tad and layer fixes and changes.
  _maps/map_files/Talos/TGS_Talos.dmm
  _maps/shuttles/minidropship_combat_tad.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  code/game/objects/machinery/door_control.dm
  code/game/objects/structures/crates_lockers/walllocker.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/window.dm
  code/game/turfs/plating.dm
  code/modules/power/lighting.dm
  code/modules/shuttle/marine_dropship.dm
  icons/UI_Icons/dropshippicker/_big.png
  icons/UI_Icons/dropshippicker/_combat_tad.png
  icons/UI_Icons/dropshippicker/_factorio.png
  icons/UI_Icons/dropshippicker/_food.png
  icons/UI_Icons/dropshippicker/_mobile_bar.png
  icons/UI_Icons/dropshippicker/_standard.png
  icons/UI_Icons/dropshippicker/_umbilical.png
  icons/obj/smooth_objects/ship_window.dmi
  icons/turf/mainship.dmi
Labels: Fix, Mapping, Sprites

#54 Update TGS_Talos
  _maps/map_files/Talos/TGS_Talos.dmm
Labels: Mapping, Marine, Feature

#58 Adds categories for panels.
  code/datums/components/rotation.dm
  code/datums/helper_datums/getrev.dm
  code/game/objects/items.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/embedding.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/taperecorder.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/pipe/construction.dm
  code/game/objects/machinery/robotic_cradle.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/preferences_verbs.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/verbs/pray.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/under.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/say.dm
  code/modules/power/generator.dm
  code/modules/tgui_panel/external.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/train.dm
Labels: QoL

#55 Movement glide
  code/__DEFINES/mobs.dm
  code/__DEFINES/movement.dm
  code/modules/mob/mob_movement.dm
Labels: QoL

#60 Motion sensor
  code/game/objects/items/motion_detector.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Marine
