Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2025-09, with the labels that each got.

#1037 Adds crawling.
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/_globalvars/bitfields.dm
  code/_onclick/human.dm
  code/datums/elements/strappable.dm
  code/datums/storage/storage.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/objs.dm
  code/modules/mob/hologram.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/predator/yautja/shield.dm
  sound/effects/footstep/crawl.ogg
Labels: Feature

#1062 Vali + Dylovene
  code/datums/components/harvester.dm
Labels: Feature

#1057 SH46 Balance
  code/modules/projectiles/ammo_datums/bullet/shotgun.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#1004 Возвращение перевода некоторых анонсов
  code/__DEFINES/mode.dm
  code/datums/gamemodes/infestation.dm
  code/game/objects/items/defibrillator.dm
  sound/effects/gladosmarinerevive.ogg
Labels: Grammar and formatting

#1091 Rank and Equipment tgui input
  code/modules/admin/topic.dm
Labels: Administration

#1075 Point bubble
  code/modules/mob/mob.dm
  icons/effects/effects.dmi
Labels: Feature

#1092 Raises ravager max health from 350 to 450.
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance

#1105 Restricts xenos from stealing items from storages.
  code/_onclick/hud/screen_objects/screen_objects.dm
Labels: Fix

#1068 'Recon' machete
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/sword.dm
  code/game/objects/machinery/vending/marine_vending/uniform.dm
  code/game/objects/machinery/vending/marine_vending/weapon.dm
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  icons/obj/items/storage/pouches.dmi
  icons/obj/items/weapons.dmi
Labels: Feature

#1110 Fixed PTRD ammo handfuls
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
Labels: Fix

#1117 Сезон тяжелого оружия
  code/controllers/subsystem/persistence.dm
Labels: Feature

#1108 Restricts assault crewman behind 35 job points.
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/shipside.dm
Labels: Balance

#1115 Fix zombie crash infinite spawning
  code/datums/gamemodes/zombie_crash.dm
Labels: Fix

#1093 New skin for drone
  code/datums/skins/_skin.dm
  code/datums/skins/drone.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/Xeno/castes/drone/hornet.dmi
  icons/Xeno/castes/drone/hornet_effects.dmi
Labels: Code Improvement, Feature

#1121 Reworks "Change Appearance" verb for xenomorphs a bit. Deletes "Make Rouny" verb
  code/__DEFINES/vv.dm
  code/datums/skins/_skin.dm
  code/datums/skins/boiler.dm
  code/datums/skins/bull.dm
  code/datums/skins/crusher.dm
  code/datums/skins/defender.dm
  code/datums/skins/defiler.dm
  code/datums/skins/drone.dm
  code/datums/skins/gorger.dm
  code/datums/skins/hivelord.dm
  code/datums/skins/panther.dm
  code/datums/skins/praetorian.dm
  code/datums/skins/queen.dm
  code/datums/skins/ravager.dm
  code/datums/skins/runner.dm
  code/datums/skins/shrike.dm
  code/datums/skins/warlock.dm
  code/datums/skins/warrior.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/smites/rounify.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/predalien.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  tgmc.dme
Labels: Removal, Code Improvement, Administration

#1120 Fixes hud/new_player harddel.
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/rendering/_plane_master.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/machinery/cic_maptable.dm
  code/modules/buildmode/buildmode.dm
  code/modules/buildmode/buttons.dm
  code/modules/mob/living/silicon/ai/multicam.dm
Labels: Fix

#1104 Distress signal 1/3 walance
  code/__DEFINES/mode.dm
Labels: Balance

#1134 Fixes balloon alert in motorbike occupants check.
  code/modules/vehicles/motorbike.dm
Labels: Fix

#1135 Ozelomelyn now doesn't have a damage cap.
  code/modules/reagents/chemistry/reagents/toxin.dm
Labels: Balance

#1100 Squad colors
  code/__DEFINES/colors.dm
  code/datums/chatmessage.dm
  code/datums/jobs/squads.dm
Labels: Feature
