Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2025-03, with the labels that each got.

#906 Delete redundant sql services.
  .github/workflows/run_integration_tests.yml
Labels: SQL

#907 Icy Caves tweaks.
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Mapping

#909 RU keybinds fix
  code/modules/client/preferences_ui.dm
Labels: Fix

#913 Reduces miner amount on Barrenquilla.
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Mapping

#914 Restricts buying factory equipment on crash.
  code/datums/gamemodes/crash.dm
  code/modules/reqs/supplypacks/_supplypacks.dm
  code/modules/reqs/ui/request.dm
Labels: Balance

#916 Facehuggers now can be killes by fire, but they can leap over it.
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance

#915 Fixes storages of large general pouch and marine shoes.
  code/datums/storage/subtypes/internal.dm
  code/game/objects/items/storage/pouch.dm
Labels: Fix

#918 Fixed item flags on sadar, minigun, sg85, b17 and b18
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#919 Facehuggers no longer die if thrown over fire.
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/marine_vending/armor.dm
  code/game/objects/machinery/vending/marine_vending/cargo.dm
  code/game/objects/machinery/vending/marine_vending/cigarette.dm
  code/game/objects/machinery/vending/marine_vending/dress.dm
  code/game/objects/machinery/vending/marine_vending/food.dm
  code/game/objects/machinery/vending/marine_vending/lasgun.dm
  code/game/objects/machinery/vending/marine_vending/med.dm
  code/game/objects/machinery/vending/marine_vending/tool.dm
  code/game/objects/machinery/vending/marine_vending/uniform.dm
  code/game/objects/machinery/vending/marine_vending/valhalla.dm
  code/game/objects/machinery/vending/marine_vending/weapon.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  tgmc.dme
Labels: Mapping, Balance

#921 Fixes surgical webbing contents.
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Fix

#922 Fixes ags magazines empty sprites.
  icons/obj/items/ammo/stationary.dmi
Labels: Fix, Sprites

#923 Fixes storages of sabre holster, corpsman satchel and bike.
  code/__DEFINES/loadout/clothes/corpsman.dm
  code/datums/storage/subtypes/holster.dm
  code/datums/storage/subtypes/internal.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/holsters.dm
Labels: Fix

#924 Shuttle now scrapes away all walls it lands on. Shuttle engines are no longer throw passable.
  code/__DEFINES/dcs/signals.dm
  code/datums/gamemodes/infestation.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/supports.dm
  code/game/objects/structures/xeno/growth.dm
  code/game/shuttle_engines.dm
  code/game/turfs/baseturf_skipover.dm
  code/game/turfs/baseturfs.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/walls.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/topic.dm
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/reqs/elevator.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_rotate.dm
  code/modules/unit_tests/connect_loc.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Fix, Feature

#926 Deletes ship map vote and change verb. Tgui-fies last admin verbs.
  code/controllers/subsystem/vote.dm
  code/datums/map_config.dm
  code/game/world.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  tgui/packages/tgui/interfaces/Vote.jsx
Labels: Removal, QoL

#928 Fixes a storage runtime (#17281)
  code/datums/storage/storage.dm
Labels: Fix, Port

#929 Deletes unused playsound in obj bullet_act.
  code/game/objects/obj_defense.dm
  code/modules/projectiles/projectile.dm
Labels: Removal, Code Improvement

#931 Weedifies Research Outpost and Orion Outpost.
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
Labels: Mapping

#932 Fixes autoweeding action icon.
  code/__DEFINES/xeno.dm
Labels: Fix

#934 Weedifies Desparity.
  _maps/map_files/desparity/desparity.dmm
Labels: Mapping

#935 Adds retired ert to eord spawn pool.
  code/modules/mob/mob_verbs.dm
Labels: Feature

#937 Xeno cleaning. Panther minor tweaks. Removes tunnel naming.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/actions/observer_action.dm
  code/datums/actions/xeno_action.dm
  code/game/data_huds/xenomorph.dm
  code/game/objects/structures/infestation_tower.dm
  code/modules/mob/camera/imaginary_friend.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/chimera/abilities_chimera.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hellhound/hellhound.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/abilities_predalien.dm
  code/modules/mob/living/carbon/xenomorph/castes/predalien/predalien.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/mob/mob_defines.dm
Labels: Removal, Code Improvement, Balance, Grammar and formatting

#938 Facehugger strip delay from 4 to 2 seconds. Sentient facehugger pounce attach range from 1 to 2.
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance
