Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2025-08, with the labels that each got.

#973 M344 pattern ammo load rig in marine vendor
  code/__DEFINES/loadout/gear/field_commander.dm
  code/__DEFINES/loadout/gear/leader.dm
  code/__DEFINES/loadout/gear/marine.dm
  code/__DEFINES/loadout/gear/smartgunner.dm
  code/datums/storage/subtypes/belt.dm
  code/game/objects/machinery/vending/marine_vending/uniform.dm
  code/modules/reqs/supplypacks/clothing.dm
Labels: Feature

#1013 Restricts warrior from using grapple toss inside crash fog.
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Feature

#1012 Планеты в зависимости от карты
  _maps/barrenquilla_mining.json
  _maps/bigred_v2.json
  _maps/deltastation.json
  _maps/desparity.json
  _maps/gelida_iv.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/kutjevo.json
  _maps/last_stand.json
  _maps/lawanka.json
  _maps/lv624.json
  _maps/magmoor_digsite_iv.json
  _maps/orion_outpost.json
  _maps/oscar_outpost.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  _maps/slumbridge.json
  _maps/vapor_processing.json
  _maps/whiskey_outpost_v2.json
  code/__DEFINES/__game.dm
  code/_onclick/hud/parallax.dm
  code/datums/map_config.dm
  icons/effects/parallax.dmi
Labels: Mapping

#1015 King's Zero Form Beam no longer goes through walls, but damages structures and machinery.
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Balance

#1011 Adds recycling cas equipment to dropship fabricator.
  code/game/objects/machinery/dropship_part_fabricator.dm
Labels: Feature

#1007 Adds plasma guns to cargo.
  code/modules/reqs/supplypacks/weapons.dm
Labels: Feature

#1023 Fob console now properly spawns materials when ejected.
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Fix

#1020 Deletes `GUN_IFF` to prevent ammo abuse for same caliber guns.
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/game/objects/machinery/vending/marine_vending/valhalla.dm
  code/modules/projectiles/ammo_datums/bullet/machinegun.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/sniper.dm
  code/modules/projectiles/ammo_datums/misc.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/projectiles/projectile.dm
Labels: Removal, Code Improvement

#1026 Imialky no longer heals tox damage.
  code/modules/reagents/chemistry/reagents/medical.dm
Labels: Balance

#997 Crash scaling walance attempt. Increases larva jobworth for FC and shipside.
  code/__DEFINES/jobs.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/crash.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/shipside.dm
Labels: Balance

#1030 Adds overcharge sniper mode description, fixes ammo hud state.
  code/modules/projectiles/ammo_datums/energy.dm
  code/modules/projectiles/guns/energy.dm
Labels: Fix, QoL

#1043 Separate assault rifles and standart rifles
  code/game/objects/machinery/vending/marine_vending/weapon.dm
Labels: QoL

#1045 Fixes examine not showing hand contents.
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/_onclick/human.dm
  code/datums/elements/strappable.dm
  code/datums/storage/storage.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/objs.dm
  code/modules/mob/hologram.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/mob_defines.dm
  sound/effects/footstep/crawl.ogg
Labels: Fix

#1051 I need a medic bag - *medic sound effect
  code/modules/mob/living/carbon/human/emote/human.dm
  sound/voice/human/male/medic_bag.ogg
Labels: Feature

#1054 Firearms implant buff
  code/game/objects/items/implants/skill/implant_types.dm
Labels: Balance
