Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2025-07, with the labels that each got.

#966 Huggers nerf
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance

#967 Readds ar-11
  code/game/objects/machinery/vending/marine_vending/weapon.dm
Labels: Feature

#980 Teleporter now beeps if the internal charge is used for teleportation. Added linking teleporter in hand to a deployed teleporter.
  code/game/objects/structures/teleporter.dm
Labels: Port, QoL

#984 Fixes laser sniper overcharge radial menu icon.
  code/modules/predator/yautja/weapons/ranged.dm
  icons/mob/radial.dmi
Labels: Fix

#983 Robotic limbs now drop themselves instead of robot parts on dismemberment.
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
Labels: Fix

#988 Adds agls inhand icons. Changes all `ags` to `agls`
  code/game/objects/items/explosives/grenades/explosive.dm
  code/game/objects/items/explosives/grenades/smoke.dm
  code/modules/projectiles/ammo_datums/artillery.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  icons/mob/inhands/gun/special_lefthand_1.dmi
  icons/mob/inhands/gun/special_righthand_1.dmi
  icons/obj/items/ammo/stationary.dmi
  icons/obj/items/grenade.dmi
  icons/obj/items/gun/hmg.dmi
  sound/weapons/guns/fire/agls.ogg
Labels: Sprites

#987 You can now jump/fly over the acid well or xeno trap. Adds ozelomelyn hugger trap sprite.
  code/__DEFINES/loadout/gear/field_commander.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/trap.dm
  icons/Xeno/Effects.dmi
Labels: Balance

#989 Adds COMSIG_CRIT_MOB.
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/living.dm
  icons/mob/inhands/gun/special_lefthand_1.dmi
  icons/mob/inhands/gun/special_righthand_1.dmi
Labels: Code Improvement

#992 Fixes empty job positions in ban panel.
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/predator.dm
  code/datums/jobs/job/som.dm
  html/browser/banpanel.css
Labels: Fix

#996 Adds psy point sources tracking. Crash shuttle landing now properly starts the generator psypoints gaining.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mode.dm
  code/controllers/subsystem/processing/resinshaping.dm
  code/controllers/subsystem/silo.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/items/cocoon.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/structures/droppod.dm
  code/modules/condor/cas_chair.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Fix, QoL, Balance
