Repository PMC-Unga-Marines/Unga-Marines, pull requests merged in 2025-04, with the labels that each got.

#905 Crush walance
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance, Stale

#942 Fixes syringe case icon. Few changes to structures ex_act's.
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/rocks.dm
  code/modules/recycling/disposal.dm
Labels: Fix, Code Improvement

#945 Makes nightvision cells properly not rechargable.
  code/game/objects/items/power_cells.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/cell_charger.dm
  code/modules/projectiles/magazines/energy.dm
Labels: Balance

#943 Fixes synth hud, flare gun inhands, mortar belt sprite and marine uniform sleeves and other.
  code/datums/components/beacon.dm
  code/game/data_huds/human.dm
  code/game/objects/items/scanners/reagent_scanner.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  icons/obj/clothing/belts.dmi
  icons/obj/items/storage/holster.dmi
  icons/obj/machines/buttons.dmi
Labels: Fix

#946 Fast cargo delivery now costs money. Adds unguided fk88 ammo as separate ammo. And a bit of fixes.
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/points.dm
  code/datums/components/beacon.dm
  code/datums/storage/storage.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/sword.dm
  code/game/objects/machinery/artillery/shell.dm
  code/game/objects/machinery/vending/marine_vending/valhalla.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks/stationary.dm
  code/modules/reqs/ui/_ui.dm
  code/modules/reqs/ui/request.dm
  code/modules/reqtorio/assembly_crafts.dm
  icons/mob/inhands/weapons/ammo_left.dmi
  icons/mob/inhands/weapons/ammo_right.dmi
  icons/mob/ties.dmi
  icons/obj/items/ammo/stationary.dmi
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: Fix, Balance, Feature

#950 Deletes ammo+ from vendors. Readds smg90 and mp17
  code/game/objects/machinery/vending/marine_vending/weapon.dm
  code/modules/projectiles/ammo_datums/bullet/pistol.dm
  code/modules/projectiles/ammo_datums/bullet/rifle.dm
  code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/reqs/supplypacks/weapons.dm
Labels: Removal, Feature

#951 Fixes xeno valhalla human spawners.
  _maps/map_files/generic/Admin_Level.dmm
Labels: Fix, Mapping
